from __future__ import annotations

import os


LANGUAGE_CODES = ("en", "ko", "ja", "zh")

_LANGUAGE_ALIASES = {
    "": "en",
    "en": "en",
    "eng": "en",
    "english": "en",
    "ko": "ko",
    "kr": "ko",
    "kor": "ko",
    "korean": "ko",
    "한국어": "ko",
    "ja": "ja",
    "jp": "ja",
    "jpn": "ja",
    "japanese": "ja",
    "日本語": "ja",
    "zh": "zh",
    "cn": "zh",
    "zho": "zh",
    "chi": "zh",
    "chinese": "zh",
    "中文": "zh",
    "简体中文": "zh",
}

LANGUAGE_NAMES = {
    "en": "English",
    "ko": "한국어",
    "ja": "日本語",
    "zh": "中文",
}

MESSAGES = {
    "en": {
        "language_title": "Setup language",
        "language_intro": "Choose the language OMH should use for this terminal setup.",
        "menu_hint": "Use ↑/↓, Space/Enter, or a number. Colors are not required.",
        "recommended": "recommended",
        "select": "Select",
        "invalid_selection": "Invalid selection. Choose one of: {valid}.",
        "invalid_yes_no": "Please answer y or n.",
        "yes": "Yes",
        "no": "No",
        "yes_desc": "Apply this setup step.",
        "no_desc": "Skip this step for now.",
        "setup_title": "OMH setup",
        "setup_subtitle": "Install OMH skills for this Hermes profile and save safe defaults.",
        "install_subtitle": "Refresh the managed Hermes skill pack.",
        "wizard_subtitle": "I will install the OMH skill pack, connect Hermes, and ask only for optional defaults. All workflows stay installed either way.",
        "hermes_home": "Hermes home",
        "hermes_config": "Hermes config",
        "managed_skills": "Managed skills",
        "status_already_registered": "already registered",
        "status_will_register": "will register OMH skills",
        "status_will_create": "will create",
        "register_question": "Register OMH skills in this Hermes profile?",
        "register_note": "This updates skills.external_dirs so Hermes can discover the managed OMH skills.",
        "executor_title": "When a request may need coding",
        "executor_intro_1": "This sets a default handoff style; it does not hide or remove any OMH skills.",
        "executor_intro_2": "Hermes can still ask, keep work in Hermes, or route to a different executor per request.",
        "executor_choose_label": "Ask me when coding is needed",
        "executor_choose_desc": "Recommended. Hermes prepares the workflow and asks before choosing Codex, Claude Code, or another executor.",
        "executor_codex_label": "Codex tracked handoff",
        "executor_codex_desc": "Use Codex as the default for implementation-shaped work and keep dispatch/result/review/CI evidence separate.",
        "executor_claude_label": "Claude Code prompt handoff",
        "executor_claude_desc": "Prepare copy-ready Claude Code prompts; OMH will not claim Claude Code ran unless a wrapper records evidence.",
        "executor_generic_label": "Portable prompt handoff",
        "executor_generic_desc": "Prepare executor-neutral prompts for any coding agent without direct dispatch.",
        "executor_hermes_label": "Keep coding-like work in Hermes",
        "executor_hermes_desc": "Keep retained planning and small changes with Hermes; larger coding can still be handed off per request.",
        "executor_runtime_label": "Plugin/runtime prompt handoff",
        "executor_runtime_desc": "Prepare OMX/OMO/OMC-style runtime prompts without assuming those runtimes are active.",
        "invalid_executor": "Invalid default executor: {error}",
        "plugin_question": "Install optional plugin bridge for local status context?",
        "plugin_note": "The plugin exposes local status context to Hermes; OMH skills work without it.",
        "team_title": "Add an optional visible team role preset?",
        "team_intro_1": "These presets add named Hermes role files. They do not enable or disable OMH workflows.",
        "team_intro_2": "Skip now unless you explicitly want startup, engineering, research, or CTO-style visible roles.",
        "team_none_label": "No extra team role preset now",
        "team_none_desc": "Recommended for first install. All OMH workflows remain installed and available.",
        "step_install_skills": "Installing managed skills",
        "step_register": "Registering Hermes skill discovery",
        "step_plugin": "Installing optional plugin bridge",
        "step_team": "Activating visible team role preset",
        "step_preferences": "Saving handoff defaults",
        "step_targets": "Detecting Hermes target topology",
        "done_skills_installed": "{count} skill(s) installed",
        "done_skills_ready": "{count} managed skill(s) ready",
        "done_profile_packs": "{count} profile pack(s) activated",
        "done_default_executor": "coding default: {executor}",
        "done_target_topology": "{mode} ({count} target(s))",
        "target_recorded": "target topology recorded",
        "skip_by_flag": "skipped by {flag}",
        "setup_complete": "OMH setup complete.",
        "setup_preview_complete": "OMH setup preview complete.",
        "install_complete": "OMH {label} complete.",
        "install_preview_complete": "OMH {label} preview complete.",
        "summary": "Summary",
        "next": "Next",
        "setup_scope": "Setup scope: {scope}",
        "setup_scope_user": "user",
        "setup_scope_custom": "custom paths",
        "setup_install_mode": "Install mode: {mode}",
        "setup_install_mode_managed_skills": "managed Hermes skills",
        "setup_mcp_mode": "MCP mode: {mode}",
        "setup_mcp_mode_none": "none",
        "setup_status": "Setup state: {status}",
        "setup_status_configured": "skills installed and Hermes registration configured",
        "setup_status_dry_run": "preview only; no local state changed",
        "setup_status_skills_only": "skills installed; Hermes registration skipped",
        "skills_line": "Skills: {count} managed skill(s) at {path}",
        "registration_configured": "Hermes registration: configured in {path} (restart or reload Hermes Agent to observe it).",
        "registration_dry_run": "Hermes registration: dry run only; no local registration was observed.",
        "registration_skipped": "Hermes registration: skipped by --skip-apply.",
        "registration_unknown": "Hermes registration: {status}",
        "apply_line": "Apply: {message}",
        "default_handoff": "Coding handoff default: {summary}",
        "setup_profile": "Routing guardrails: {selected}",
        "target_topology": "Target topology: {mode} ({count} known target(s)).",
        "plugin_bridge": "Plugin bridge: {status}",
        "plugin_optional": "Plugin bridge: optional; install later with `omh setup --with-plugin`.",
        "team_activated": "Visible team preset: {count} profile pack(s) activated.",
        "team_none": "Visible team preset: none selected; all OMH workflows remain installed.",
        "setup_next_dry": "Rerun without `--dry-run` to install and register the managed skills.",
        "setup_next_reload": "Restart or reload Hermes Agent, then try this in Hermes chat:",
        "setup_next_prompt": "Ask Hermes: Use OMH request-to-handoff for: I want to safely add a feature to this repo.",
        "machine_readable": "For machine-readable output, rerun with `--json`.",
        "source": "Source: {source}",
        "source_builtin": "installed command package (builtin)",
        "release_channel": "Release channel: {channel}",
        "package_url": "Package URL: {url}",
        "recorded_package_url": "Recorded package URL: {url}",
        "release_version_change": "Release version: {change}",
        "release_source_ref_change": "Source ref: {change}",
        "release_update_status": "Release state: {status}",
        "command_package_updated": "Command package: updated by installer before this OMH setup/update run.",
        "command_package_unchanged": "Command package: unchanged; this command refreshed the managed skills from the currently installed OMH package.",
        "update_command_next": "To update the `omh` command itself, rerun the installer: curl -fsSL https://raw.githubusercontent.com/rlaope/oh-my-hermes-agent/main/install.sh | sh",
        "state_log": "State log: {path} ({entry})",
        "install_next_dry": "Rerun without `--dry-run` to refresh the managed skills.",
        "install_next": "Run `omh setup` to connect skills to Hermes, or `omh doctor` to verify health.",
        "update_next": "Run `omh doctor` to verify health; run `omh setup` only if registration needs repair.",
        "doctor_complete": "OMH doctor complete.",
        "doctor_needs_attention": "OMH doctor needs attention.",
        "doctor_status": "Status: {status}",
        "doctor_status_ok": "ok",
        "doctor_status_needs_attention": "needs attention",
        "doctor_checks": "Checks: {passing}/{total} passing",
        "doctor_issue_counts": "Issues: {blocking} blocking, {warnings} warning(s)",
        "doctor_group_managed_skills": "Managed skills",
        "doctor_group_runtime": "Runtime state",
        "doctor_group_hermes_registration": "Hermes registration",
        "doctor_group_targets": "Hermes targets",
        "doctor_group_optional_surfaces": "Optional surfaces",
        "doctor_group_status_ok": "ok",
        "doctor_group_status_warning": "warning",
        "doctor_group_status_needs_attention": "needs attention",
        "doctor_fix": "Fix",
        "doctor_boundary": "Boundary: restart or reload Hermes before treating chat visibility as observed.",
        "config_external_dir_already_present": "already configured",
        "config_created_skills_external_dirs": "created Hermes skills registration",
        "config_appended_skills_external_dirs": "added Hermes skills registration",
        "config_expanded_inline_external_dirs": "expanded Hermes skills registration",
        "config_inserted_skills_external_dirs": "inserted Hermes skills registration",
        "config_added_external_dir": "added OMH skills directory",
        "config_external_dir_absent": "already removed",
        "config_removed_external_dir": "removed OMH skills directory",
        "uninstall_title": "OMH uninstall",
        "uninstall_subtitle": "Remove OMH-managed local state and Hermes integration files.",
        "uninstall_complete": "OMH uninstall complete.",
        "uninstall_preview_complete": "OMH uninstall preview complete.",
        "uninstall_scope_all": "full cleanup",
        "uninstall_scope_registration": "registration only",
        "uninstall_scope_files": "registration and managed ~/.omh files",
        "uninstall_config": "Hermes registration: {message}",
        "uninstall_removed": "Removed: {count} path(s)",
        "uninstall_would_remove": "Would remove: {count} path(s)",
        "uninstall_none": "Nothing to remove.",
        "uninstall_command_removed": "Command package: removed {count} install.sh-managed path(s).",
        "uninstall_command_would_remove": "Command package: would remove {count} install.sh-managed path(s).",
        "uninstall_command_kept": "Command package: not removed because this `omh` is not running from an install.sh-managed OMH venv.",
        "uninstall_command_still_available": "If `omh` still runs after uninstall, the command package is still on PATH; remove it with the installer-managed venv, pip, or pipx that installed it.",
        "scope": "Scope",
        "kept": "Kept",
    },
    "ko": {
        "language_title": "설치 언어",
        "language_intro": "이 터미널 설치에서 OMH가 사용할 언어를 선택합니다.",
        "menu_hint": "↑/↓, Space/Enter, 숫자로 선택할 수 있습니다. 색상 없이도 동작합니다.",
        "recommended": "추천",
        "select": "선택",
        "invalid_selection": "잘못된 선택입니다. 다음 중 하나를 선택하세요: {valid}.",
        "invalid_yes_no": "y 또는 n으로 답해주세요.",
        "yes": "예",
        "no": "아니요",
        "yes_desc": "이 설정 단계를 적용합니다.",
        "no_desc": "지금은 이 단계를 건너뜁니다.",
        "setup_title": "OMH 설정",
        "setup_subtitle": "이 Hermes 프로필에 OMH 스킬을 설치하고 안전한 기본값을 저장합니다.",
        "install_subtitle": "관리 Hermes 스킬팩을 갱신합니다.",
        "wizard_subtitle": "OMH 스킬팩을 설치하고 Hermes에 연결한 뒤, 선택형 기본값만 묻겠습니다. 모든 워크플로는 동일하게 설치됩니다.",
        "hermes_home": "Hermes 홈",
        "hermes_config": "Hermes 설정",
        "managed_skills": "관리 스킬",
        "status_already_registered": "이미 등록됨",
        "status_will_register": "OMH 스킬 등록 예정",
        "status_will_create": "생성 예정",
        "register_question": "이 Hermes 프로필에 OMH 스킬을 등록할까요?",
        "register_note": "Hermes가 OMH 관리 스킬을 찾을 수 있도록 skills.external_dirs를 업데이트합니다.",
        "executor_title": "코딩이 필요할 수 있는 요청",
        "executor_intro_1": "이 값은 기본 handoff 방식입니다. 어떤 OMH 스킬도 숨기거나 제거하지 않습니다.",
        "executor_intro_2": "Hermes는 요청별로 다시 묻거나, Hermes 안에 유지하거나, 다른 실행자로 보낼 수 있습니다.",
        "executor_choose_label": "코딩이 필요할 때 물어보기",
        "executor_choose_desc": "추천. Hermes가 워크플로를 준비한 뒤 Codex, Claude Code, 다른 실행자 중 무엇을 쓸지 묻습니다.",
        "executor_codex_label": "Codex 추적 handoff",
        "executor_codex_desc": "구현형 작업의 기본 실행자로 Codex를 쓰고 dispatch/result/review/CI evidence를 분리합니다.",
        "executor_claude_label": "Claude Code 프롬프트 handoff",
        "executor_claude_desc": "복사해서 쓸 수 있는 Claude Code 프롬프트를 준비합니다. wrapper evidence 없이는 실행됐다고 말하지 않습니다.",
        "executor_generic_label": "범용 프롬프트 handoff",
        "executor_generic_desc": "직접 dispatch 없이 어떤 코딩 에이전트에도 줄 수 있는 중립 프롬프트를 준비합니다.",
        "executor_hermes_label": "코딩 유사 작업을 Hermes에 유지",
        "executor_hermes_desc": "계획과 작은 변경은 Hermes에 두고, 큰 코딩은 요청별로 handoff할 수 있게 합니다.",
        "executor_runtime_label": "플러그인/런타임 프롬프트 handoff",
        "executor_runtime_desc": "OMX/OMO/OMC식 런타임 프롬프트를 준비하되, 런타임이 실행 중이라고 가정하지 않습니다.",
        "invalid_executor": "기본 실행자 값이 올바르지 않습니다: {error}",
        "plugin_question": "로컬 상태 맥락용 선택형 플러그인 브리지를 설치할까요?",
        "plugin_note": "플러그인은 Hermes에 로컬 상태 맥락을 제공합니다. OMH 스킬은 플러그인 없이도 동작합니다.",
        "team_title": "선택형 보이는 팀 역할 프리셋을 추가할까요?",
        "team_intro_1": "이 프리셋은 이름 있는 Hermes 역할 파일을 추가합니다. OMH 워크플로를 켜거나 끄는 선택이 아닙니다.",
        "team_intro_2": "startup, engineering, research, CTO식 보이는 역할을 명시적으로 원할 때만 선택하세요.",
        "team_none_label": "지금은 추가 팀 역할 프리셋 없음",
        "team_none_desc": "첫 설치에 추천합니다. 모든 OMH 워크플로는 그대로 설치되고 사용할 수 있습니다.",
        "step_install_skills": "관리 스킬 설치",
        "step_register": "Hermes 스킬 탐색 등록",
        "step_plugin": "선택형 플러그인 브리지 설치",
        "step_team": "보이는 팀 역할 프리셋 활성화",
        "step_preferences": "handoff 기본값 저장",
        "step_targets": "Hermes 대상 토폴로지 감지",
        "done_skills_installed": "{count}개 스킬 설치 완료",
        "done_skills_ready": "{count}개 관리 스킬 준비 완료",
        "done_profile_packs": "{count}개 프로필 팩 활성화",
        "done_default_executor": "코딩 기본값: {executor}",
        "done_target_topology": "{mode} ({count}개 대상)",
        "target_recorded": "대상 토폴로지 기록 완료",
        "skip_by_flag": "{flag} 때문에 건너뜀",
        "setup_complete": "OMH 설정이 완료되었습니다.",
        "setup_preview_complete": "OMH 설정 미리보기가 완료되었습니다.",
        "install_complete": "OMH {label} 완료.",
        "install_preview_complete": "OMH {label} 미리보기 완료.",
        "summary": "요약",
        "next": "다음",
        "setup_scope": "설정 범위: {scope}",
        "setup_scope_user": "사용자",
        "setup_scope_custom": "사용자 지정 경로",
        "setup_install_mode": "설치 모드: {mode}",
        "setup_install_mode_managed_skills": "관리 Hermes 스킬",
        "setup_mcp_mode": "MCP 모드: {mode}",
        "setup_mcp_mode_none": "없음",
        "setup_status": "설정 상태: {status}",
        "setup_status_configured": "스킬 설치 및 Hermes 등록 완료",
        "setup_status_dry_run": "미리보기만 수행; 로컬 상태 변경 없음",
        "setup_status_skills_only": "스킬 설치 완료; Hermes 등록 건너뜀",
        "skills_line": "스킬: {path}에 {count}개 관리 스킬",
        "registration_configured": "Hermes 등록: {path}에 설정됨 (Hermes Agent를 재시작하거나 다시 불러오면 반영됩니다).",
        "registration_dry_run": "Hermes 등록: dry-run이라 로컬 등록은 관측되지 않았습니다.",
        "registration_skipped": "Hermes 등록: --skip-apply로 건너뜀.",
        "registration_unknown": "Hermes 등록: {status}",
        "apply_line": "적용: {message}",
        "default_handoff": "코딩 handoff 기본값: {summary}",
        "setup_profile": "라우팅 안전장치: {selected}",
        "target_topology": "대상 토폴로지: {mode} ({count}개 알려진 대상).",
        "plugin_bridge": "플러그인 브리지: {status}",
        "plugin_optional": "플러그인 브리지: 선택 사항입니다. 나중에 `omh setup --with-plugin`로 설치할 수 있습니다.",
        "team_activated": "보이는 팀 프리셋: {count}개 프로필 팩 활성화.",
        "team_none": "보이는 팀 프리셋: 선택 안 함. 모든 OMH 워크플로는 그대로 설치되어 있습니다.",
        "setup_next_dry": "`--dry-run` 없이 다시 실행하면 관리 스킬을 설치하고 등록합니다.",
        "setup_next_reload": "Hermes Agent를 재시작하거나 다시 불러온 뒤 Hermes 채팅에서 시도하세요:",
        "setup_next_prompt": "Hermes에게 말해보세요: Use OMH request-to-handoff for: I want to safely add a feature to this repo.",
        "machine_readable": "기계가 읽는 출력이 필요하면 `--json`으로 다시 실행하세요.",
        "source": "소스: {source}",
        "source_builtin": "설치된 명령 패키지(builtin)",
        "release_channel": "릴리즈 채널: {channel}",
        "package_url": "패키지 URL: {url}",
        "recorded_package_url": "기록된 패키지 URL: {url}",
        "release_version_change": "릴리즈 버전: {change}",
        "release_source_ref_change": "소스 ref: {change}",
        "release_update_status": "릴리즈 상태: {status}",
        "command_package_updated": "명령 패키지: 설치 스크립트가 이번 OMH setup/update 실행 전에 갱신했습니다.",
        "command_package_unchanged": "명령 패키지: 변경하지 않았습니다. 이 명령은 현재 설치된 OMH 패키지에서 관리 스킬만 갱신했습니다.",
        "update_command_next": "`omh` 명령 자체를 갱신하려면 설치 스크립트를 다시 실행하세요: curl -fsSL https://raw.githubusercontent.com/rlaope/oh-my-hermes-agent/main/install.sh | sh",
        "state_log": "상태 로그: {path} ({entry})",
        "install_next_dry": "`--dry-run` 없이 다시 실행하면 관리 스킬을 갱신합니다.",
        "install_next": "`omh setup`으로 스킬을 Hermes에 연결하거나 `omh doctor`로 상태를 확인하세요.",
        "update_next": "`omh doctor`로 상태를 확인하세요. 등록 복구가 필요할 때만 `omh setup`을 실행하세요.",
        "doctor_complete": "OMH doctor가 완료되었습니다.",
        "doctor_needs_attention": "OMH doctor에 확인이 필요합니다.",
        "doctor_status": "상태: {status}",
        "doctor_status_ok": "정상",
        "doctor_status_needs_attention": "확인 필요",
        "doctor_checks": "검사: {passing}/{total} 통과",
        "doctor_issue_counts": "이슈: 차단 {blocking}개, 경고 {warnings}개",
        "doctor_group_managed_skills": "관리 스킬",
        "doctor_group_runtime": "런타임 상태",
        "doctor_group_hermes_registration": "Hermes 등록",
        "doctor_group_targets": "Hermes 대상",
        "doctor_group_optional_surfaces": "선택형 표면",
        "doctor_group_status_ok": "정상",
        "doctor_group_status_warning": "경고",
        "doctor_group_status_needs_attention": "확인 필요",
        "doctor_fix": "수정",
        "doctor_boundary": "경계: Hermes 채팅 노출을 관측된 것으로 보기 전에 Hermes를 재시작하거나 다시 불러오세요.",
        "config_external_dir_already_present": "이미 설정됨",
        "config_created_skills_external_dirs": "Hermes 스킬 등록 생성",
        "config_appended_skills_external_dirs": "Hermes 스킬 등록 추가",
        "config_expanded_inline_external_dirs": "Hermes 스킬 등록 확장",
        "config_inserted_skills_external_dirs": "Hermes 스킬 등록 삽입",
        "config_added_external_dir": "OMH 스킬 디렉터리 추가",
        "config_external_dir_absent": "이미 제거됨",
        "config_removed_external_dir": "OMH 스킬 디렉터리 제거",
        "uninstall_title": "OMH 삭제",
        "uninstall_subtitle": "OMH가 관리하는 로컬 상태와 Hermes 연동 파일을 제거합니다.",
        "uninstall_complete": "OMH 삭제가 완료되었습니다.",
        "uninstall_preview_complete": "OMH 삭제 미리보기가 완료되었습니다.",
        "uninstall_scope_all": "전체 정리",
        "uninstall_scope_registration": "등록만 해제",
        "uninstall_scope_files": "등록과 관리 ~/.omh 파일 삭제",
        "uninstall_config": "Hermes 등록: {message}",
        "uninstall_removed": "삭제됨: {count}개 경로",
        "uninstall_would_remove": "삭제 예정: {count}개 경로",
        "uninstall_none": "삭제할 항목이 없습니다.",
        "uninstall_command_removed": "명령 패키지: install.sh가 관리하는 {count}개 경로를 삭제했습니다.",
        "uninstall_command_would_remove": "명령 패키지: install.sh가 관리하는 {count}개 경로를 삭제할 예정입니다.",
        "uninstall_command_kept": "명령 패키지: 이 `omh`가 install.sh 관리 OMH venv에서 실행 중이 아니어서 삭제하지 않았습니다.",
        "uninstall_command_still_available": "uninstall 뒤에도 `omh`가 실행된다면 명령 패키지가 아직 PATH에 남아 있는 것입니다. 설치에 사용한 installer-managed venv, pip, 또는 pipx에서 제거하세요.",
        "scope": "범위",
        "kept": "유지됨",
    },
    "ja": {
        "language_title": "セットアップ言語",
        "language_intro": "このターミナルセットアップで OMH が使う言語を選びます。",
        "menu_hint": "↑/↓、Space/Enter、または数字で選択できます。色なしでも動作します。",
        "recommended": "推奨",
        "select": "選択",
        "invalid_selection": "無効な選択です。次から選んでください: {valid}.",
        "invalid_yes_no": "y または n で答えてください。",
        "yes": "はい",
        "no": "いいえ",
        "yes_desc": "このセットアップ手順を適用します。",
        "no_desc": "今回はこの手順をスキップします。",
        "setup_title": "OMH セットアップ",
        "setup_subtitle": "インストール済みの OMH ワークフローをこの Hermes プロファイルに接続します。",
        "install_subtitle": "管理 Hermes スキルパックを更新します。",
        "wizard_subtitle": "OMH スキルパックをインストールし、Hermes に接続し、実行動作が変わる選択だけを確認します。",
        "hermes_home": "Hermes ホーム",
        "hermes_config": "Hermes 設定",
        "managed_skills": "管理スキル",
        "status_already_registered": "登録済み",
        "status_will_register": "OMH スキルを登録予定",
        "status_will_create": "作成予定",
        "register_question": "この Hermes プロファイルに OMH スキルを登録しますか?",
        "register_note": "Hermes が管理 OMH スキルを検出できるように skills.external_dirs を更新します。",
        "executor_title": "コーディング系リクエストの既定動作",
        "executor_intro_1": "これは既定値です。OMH スキルはどの選択でもすべてインストールされます。",
        "executor_intro_2": "Hermes はリクエストに応じて確認したり別ルートへ送ったりできます。",
        "executor_choose_label": "コーディングが必要な時に確認",
        "executor_choose_desc": "推奨。Hermes がワークフローを準備し、Codex、Claude Code、別の実行者のどれを使うか確認します。",
        "executor_codex_label": "Codex 追跡 handoff",
        "executor_codex_desc": "実装系作業の既定を Codex にし、dispatch/result/review/CI の evidence を分離します。",
        "executor_claude_label": "Claude Code プロンプト handoff",
        "executor_claude_desc": "コピー可能な Claude Code プロンプトを準備します。wrapper evidence がなければ実行済みとは主張しません。",
        "executor_generic_label": "汎用プロンプト handoff",
        "executor_generic_desc": "直接 dispatch せず、任意の coding agent に渡せる中立プロンプトを準備します。",
        "executor_hermes_label": "コーディングに近い作業を Hermes に保持",
        "executor_hermes_desc": "計画と小さな変更は Hermes に残し、大きなコーディングはリクエストごとに handoff できます。",
        "executor_runtime_label": "プラグイン/ランタイム用プロンプト handoff",
        "executor_runtime_desc": "OMX/OMO/OMC 形式のランタイムプロンプトを準備しますが、実行中とは仮定しません。",
        "invalid_executor": "既定実行者が無効です: {error}",
        "plugin_question": "任意のプラグインブリッジをインストールしますか?",
        "plugin_note": "プラグインは Hermes にローカル状態の文脈を渡します。OMH スキルはプラグインなしでも動作します。",
        "team_title": "表示用チームペルソナを今有効化しますか?",
        "team_intro_1": "これは任意の Hermes ロールファイルで、欠けている機能ではありません。",
        "team_intro_2": "あとで `omh setup --profile-pack <id>` で追加できます。",
        "team_none_label": "今は追加チームペルソナなし",
        "team_none_desc": "初回インストールに推奨。すべての OMH ワークフローは引き続き利用できます。",
        "step_install_skills": "管理スキルをインストール",
        "step_register": "Hermes スキル検出を登録",
        "step_plugin": "任意のプラグインブリッジをインストール",
        "step_team": "表示用チームロールプリセットを有効化",
        "step_preferences": "ルーティング設定を保存",
        "step_targets": "Hermes ターゲット構成を検出",
        "done_skills_installed": "{count} 個のスキルをインストールしました",
        "done_skills_ready": "{count} 個の管理スキルを準備しました",
        "done_profile_packs": "{count} 個のプロファイルパックを有効化しました",
        "done_default_executor": "既定実行者: {executor}",
        "done_target_topology": "{mode} ({count} ターゲット)",
        "target_recorded": "ターゲット構成を記録しました",
        "skip_by_flag": "{flag} によりスキップ",
        "setup_complete": "OMH セットアップが完了しました。",
        "setup_preview_complete": "OMH セットアップのプレビューが完了しました。",
        "install_complete": "OMH {label} が完了しました。",
        "install_preview_complete": "OMH {label} のプレビューが完了しました。",
        "summary": "概要",
        "next": "次",
        "setup_scope": "セットアップスコープ: {scope}",
        "setup_scope_user": "ユーザー",
        "setup_scope_custom": "カスタムパス",
        "setup_install_mode": "インストールモード: {mode}",
        "setup_install_mode_managed_skills": "管理 Hermes スキル",
        "setup_mcp_mode": "MCP モード: {mode}",
        "setup_mcp_mode_none": "なし",
        "setup_status": "セットアップ状態: {status}",
        "setup_status_configured": "スキルをインストールし Hermes 登録を設定済み",
        "setup_status_dry_run": "プレビューのみ。ローカル状態は変更していません",
        "setup_status_skills_only": "スキルをインストール済み。Hermes 登録はスキップ",
        "skills_line": "スキル: {path} に {count} 個の管理スキル",
        "registration_configured": "Hermes 登録: {path} に設定済み (Hermes Agent を再起動または再読み込みすると反映されます)。",
        "registration_dry_run": "Hermes 登録: dry-run のためローカル登録は観測されていません。",
        "registration_skipped": "Hermes 登録: --skip-apply によりスキップ。",
        "registration_unknown": "Hermes 登録: {status}",
        "apply_line": "適用: {message}",
        "default_handoff": "既定 handoff: {summary}",
        "setup_profile": "セットアッププロファイル: {selected}",
        "target_topology": "ターゲット構成: {mode} ({count} 既知ターゲット).",
        "plugin_bridge": "プラグインブリッジ: {status}",
        "plugin_optional": "プラグインブリッジ: 任意です。あとで `omh setup --with-plugin` でインストールできます。",
        "team_activated": "チームペルソナ: {count} 個のプロファイルパックを有効化。",
        "team_none": "チームペルソナ: 未有効化。すべての OMH ワークフローはインストール済みです。",
        "setup_next_dry": "`--dry-run` なしで再実行すると、管理スキルをインストールして登録します。",
        "setup_next_reload": "Hermes Agent を再起動または再読み込みし、Hermes チャットで試してください:",
        "setup_next_prompt": "Use OMH request-to-handoff for: I want to safely add a feature to this repo.",
        "machine_readable": "機械可読出力が必要な場合は `--json` を付けて再実行してください。",
        "source": "ソース: {source}",
        "source_builtin": "インストール済みコマンドパッケージ (builtin)",
        "release_channel": "リリースチャンネル: {channel}",
        "package_url": "パッケージ URL: {url}",
        "recorded_package_url": "記録されたパッケージ URL: {url}",
        "release_version_change": "リリースバージョン: {change}",
        "release_source_ref_change": "ソース ref: {change}",
        "release_update_status": "リリース状態: {status}",
        "command_package_updated": "コマンドパッケージ: インストーラーがこの OMH setup/update 実行前に更新しました。",
        "command_package_unchanged": "コマンドパッケージ: 変更していません。このコマンドは現在インストール済みの OMH パッケージから管理スキルだけを更新しました。",
        "update_command_next": "`omh` コマンド自体を更新するにはインストーラーを再実行してください: curl -fsSL https://raw.githubusercontent.com/rlaope/oh-my-hermes-agent/main/install.sh | sh",
        "state_log": "状態ログ: {path} ({entry})",
        "install_next_dry": "`--dry-run` なしで再実行すると管理スキルを更新します。",
        "install_next": "`omh setup` で Hermes 登録を修復するか、`omh doctor` で状態を確認してください。",
        "update_next": "`omh doctor` で状態を確認してください。登録の修復が必要な場合だけ `omh setup` を実行してください。",
        "doctor_complete": "OMH doctor が完了しました。",
        "doctor_needs_attention": "OMH doctor は確認が必要です。",
        "doctor_status": "状態: {status}",
        "doctor_status_ok": "ok",
        "doctor_status_needs_attention": "要確認",
        "doctor_checks": "チェック: {passing}/{total} 合格",
        "doctor_issue_counts": "問題: ブロック {blocking} 件、警告 {warnings} 件",
        "doctor_group_managed_skills": "管理スキル",
        "doctor_group_runtime": "ランタイム状態",
        "doctor_group_hermes_registration": "Hermes 登録",
        "doctor_group_targets": "Hermes ターゲット",
        "doctor_group_optional_surfaces": "任意サーフェス",
        "doctor_group_status_ok": "ok",
        "doctor_group_status_warning": "警告",
        "doctor_group_status_needs_attention": "要確認",
        "doctor_fix": "修正",
        "doctor_boundary": "境界: チャット表示を観測済みと扱う前に Hermes を再起動または再読み込みしてください。",
        "config_external_dir_already_present": "すでに設定済み",
        "config_created_skills_external_dirs": "Hermes スキル登録を作成",
        "config_appended_skills_external_dirs": "Hermes スキル登録を追加",
        "config_expanded_inline_external_dirs": "Hermes スキル登録を展開",
        "config_inserted_skills_external_dirs": "Hermes スキル登録を挿入",
        "config_added_external_dir": "OMH スキルディレクトリを追加",
        "config_external_dir_absent": "すでに削除済み",
        "config_removed_external_dir": "OMH スキルディレクトリを削除",
        "uninstall_title": "OMH アンインストール",
        "uninstall_subtitle": "OMH が管理するローカル状態と Hermes 連携ファイルを削除します。",
        "uninstall_complete": "OMH アンインストールが完了しました。",
        "uninstall_preview_complete": "OMH アンインストールのプレビューが完了しました。",
        "uninstall_scope_all": "完全クリーンアップ",
        "uninstall_scope_registration": "登録のみ解除",
        "uninstall_scope_files": "登録と管理 ~/.omh ファイルを削除",
        "uninstall_config": "Hermes 登録: {message}",
        "uninstall_removed": "削除済み: {count} パス",
        "uninstall_would_remove": "削除予定: {count} パス",
        "uninstall_none": "削除する項目はありません。",
        "uninstall_command_removed": "コマンドパッケージ: install.sh 管理の {count} パスを削除しました。",
        "uninstall_command_would_remove": "コマンドパッケージ: install.sh 管理の {count} パスを削除予定です。",
        "uninstall_command_kept": "コマンドパッケージ: この `omh` は install.sh 管理の OMH venv から実行されていないため削除しませんでした。",
        "uninstall_command_still_available": "uninstall 後も `omh` が動く場合、コマンドパッケージがまだ PATH に残っています。インストールに使った installer-managed venv、pip、または pipx から削除してください。",
        "scope": "範囲",
        "kept": "保持",
    },
    "zh": {
        "language_title": "设置语言",
        "language_intro": "选择 OMH 在本次终端设置中使用的语言。",
        "menu_hint": "可用 ↑/↓、Space/Enter 或数字选择。无颜色也可使用。",
        "recommended": "推荐",
        "select": "选择",
        "invalid_selection": "无效选择。请选择: {valid}.",
        "invalid_yes_no": "请回答 y 或 n。",
        "yes": "是",
        "no": "否",
        "yes_desc": "应用此设置步骤。",
        "no_desc": "暂时跳过此步骤。",
        "setup_title": "OMH 设置",
        "setup_subtitle": "将已安装的 OMH 工作流连接到此 Hermes 配置。",
        "install_subtitle": "刷新托管 Hermes 技能包。",
        "wizard_subtitle": "我会安装 OMH 技能包、连接 Hermes，并只询问会改变运行行为的选项。",
        "hermes_home": "Hermes 主目录",
        "hermes_config": "Hermes 配置",
        "managed_skills": "托管技能",
        "status_already_registered": "已注册",
        "status_will_register": "将注册 OMH 技能",
        "status_will_create": "将创建",
        "register_question": "是否在此 Hermes 配置中注册 OMH 技能?",
        "register_note": "这会更新 skills.external_dirs，让 Hermes 能发现托管的 OMH 技能。",
        "executor_title": "编码类请求的默认处理",
        "executor_intro_1": "这只是默认值。无论选择什么，所有 OMH 技能都会安装。",
        "executor_intro_2": "Hermes 仍可根据请求再次询问或使用不同路由。",
        "executor_choose_label": "需要编码时询问我",
        "executor_choose_desc": "推荐。Hermes 先准备工作流，再询问使用 Codex、Claude Code 或其他执行器。",
        "executor_codex_label": "Codex 跟踪 handoff",
        "executor_codex_desc": "将 Codex 作为实现类工作的默认执行器，并分离 dispatch/result/review/CI evidence。",
        "executor_claude_label": "Claude Code 提示词 handoff",
        "executor_claude_desc": "准备可复制的 Claude Code 提示词；没有 wrapper evidence 时不会声称 Claude Code 已运行。",
        "executor_generic_label": "通用提示词 handoff",
        "executor_generic_desc": "准备不直接 dispatch、可交给任意编码 agent 的中立提示词。",
        "executor_hermes_label": "将类似编码的工作保留在 Hermes",
        "executor_hermes_desc": "研究、计划和小变更保留在 Hermes；较大的编码仍可按请求 handoff。",
        "executor_runtime_label": "插件/运行时提示词 handoff",
        "executor_runtime_desc": "准备 OMX/OMO/OMC 风格运行时提示词，但不假设这些运行时已启动。",
        "invalid_executor": "默认执行器无效: {error}",
        "plugin_question": "是否安装可选插件桥?",
        "plugin_note": "插件向 Hermes 提供本地状态上下文；OMH 技能无需插件也能工作。",
        "team_title": "现在添加可见团队角色预设吗?",
        "team_intro_1": "这些是可选 Hermes 角色文件，不是缺失功能。",
        "team_intro_2": "以后可用 `omh setup --profile-pack <id>` 添加。",
        "team_none_label": "现在不添加团队角色预设",
        "team_none_desc": "首次安装推荐。所有 OMH 工作流仍会安装并可用。",
        "step_install_skills": "安装托管技能",
        "step_register": "注册 Hermes 技能发现",
        "step_plugin": "安装可选插件桥",
        "step_team": "启用可见团队角色预设",
        "step_preferences": "保存路由偏好",
        "step_targets": "检测 Hermes 目标拓扑",
        "done_skills_installed": "已安装 {count} 个技能",
        "done_skills_ready": "已准备 {count} 个托管技能",
        "done_profile_packs": "已启用 {count} 个配置包",
        "done_default_executor": "默认执行器: {executor}",
        "done_target_topology": "{mode} ({count} 个目标)",
        "target_recorded": "已记录目标拓扑",
        "skip_by_flag": "因 {flag} 跳过",
        "setup_complete": "OMH 设置已完成。",
        "setup_preview_complete": "OMH 设置预览已完成。",
        "install_complete": "OMH {label} 已完成。",
        "install_preview_complete": "OMH {label} 预览已完成。",
        "summary": "摘要",
        "next": "下一步",
        "setup_scope": "设置范围: {scope}",
        "setup_scope_user": "用户",
        "setup_scope_custom": "自定义路径",
        "setup_install_mode": "安装模式: {mode}",
        "setup_install_mode_managed_skills": "托管 Hermes 技能",
        "setup_mcp_mode": "MCP 模式: {mode}",
        "setup_mcp_mode_none": "无",
        "setup_status": "设置状态: {status}",
        "setup_status_configured": "技能已安装且 Hermes 注册已配置",
        "setup_status_dry_run": "仅预览；未更改本地状态",
        "setup_status_skills_only": "技能已安装；已跳过 Hermes 注册",
        "skills_line": "技能: {path} 中有 {count} 个托管技能",
        "registration_configured": "Hermes 注册: 已写入 {path} (重启或重新加载 Hermes Agent 后生效)。",
        "registration_dry_run": "Hermes 注册: 仅 dry-run，未观察到本地注册。",
        "registration_skipped": "Hermes 注册: 因 --skip-apply 跳过。",
        "registration_unknown": "Hermes 注册: {status}",
        "apply_line": "应用: {message}",
        "default_handoff": "默认 handoff: {summary}",
        "setup_profile": "设置配置: {selected}",
        "target_topology": "目标拓扑: {mode} ({count} 个已知目标).",
        "plugin_bridge": "插件桥: {status}",
        "plugin_optional": "插件桥: 可选；之后可用 `omh setup --with-plugin` 安装。",
        "team_activated": "可见团队预设: 已启用 {count} 个配置包。",
        "team_none": "可见团队预设: 未选择；所有 OMH 工作流仍已安装。",
        "setup_next_dry": "不带 `--dry-run` 重新运行即可安装并注册托管技能。",
        "setup_next_reload": "重启或重新加载 Hermes Agent，然后在 Hermes 聊天中尝试:",
        "setup_next_prompt": "Use OMH request-to-handoff for: I want to safely add a feature to this repo.",
        "machine_readable": "如需机器可读输出，请使用 `--json` 重新运行。",
        "source": "来源: {source}",
        "source_builtin": "已安装命令包 (builtin)",
        "release_channel": "发布频道: {channel}",
        "package_url": "包 URL: {url}",
        "recorded_package_url": "已记录包 URL: {url}",
        "release_version_change": "发布版本: {change}",
        "release_source_ref_change": "来源 ref: {change}",
        "release_update_status": "发布状态: {status}",
        "command_package_updated": "命令包: 安装器已在本次 OMH setup/update 运行前更新。",
        "command_package_unchanged": "命令包: 未更改；此命令只从当前已安装的 OMH 包刷新托管技能。",
        "update_command_next": "要更新 `omh` 命令本身，请重新运行安装器: curl -fsSL https://raw.githubusercontent.com/rlaope/oh-my-hermes-agent/main/install.sh | sh",
        "state_log": "状态日志: {path} ({entry})",
        "install_next_dry": "不带 `--dry-run` 重新运行即可刷新托管技能。",
        "install_next": "运行 `omh setup` 修复 Hermes 注册，或运行 `omh doctor` 检查健康状态。",
        "update_next": "运行 `omh doctor` 检查健康状态；只有注册需要修复时才运行 `omh setup`。",
        "doctor_complete": "OMH doctor 完成。",
        "doctor_needs_attention": "OMH doctor 需要处理。",
        "doctor_status": "状态: {status}",
        "doctor_status_ok": "正常",
        "doctor_status_needs_attention": "需要处理",
        "doctor_checks": "检查: {passing}/{total} 通过",
        "doctor_issue_counts": "问题: {blocking} 个阻塞，{warnings} 个警告",
        "doctor_group_managed_skills": "托管技能",
        "doctor_group_runtime": "运行时状态",
        "doctor_group_hermes_registration": "Hermes 注册",
        "doctor_group_targets": "Hermes 目标",
        "doctor_group_optional_surfaces": "可选表面",
        "doctor_group_status_ok": "正常",
        "doctor_group_status_warning": "警告",
        "doctor_group_status_needs_attention": "需要处理",
        "doctor_fix": "修复",
        "doctor_boundary": "边界: 在把聊天可见性视为已观察之前，请重启或重新加载 Hermes。",
        "config_external_dir_already_present": "已配置",
        "config_created_skills_external_dirs": "已创建 Hermes 技能注册",
        "config_appended_skills_external_dirs": "已添加 Hermes 技能注册",
        "config_expanded_inline_external_dirs": "已扩展 Hermes 技能注册",
        "config_inserted_skills_external_dirs": "已插入 Hermes 技能注册",
        "config_added_external_dir": "已添加 OMH 技能目录",
        "config_external_dir_absent": "已移除",
        "config_removed_external_dir": "已移除 OMH 技能目录",
        "uninstall_title": "OMH 卸载",
        "uninstall_subtitle": "删除 OMH 管理的本地状态和 Hermes 集成文件。",
        "uninstall_complete": "OMH 卸载已完成。",
        "uninstall_preview_complete": "OMH 卸载预览已完成。",
        "uninstall_scope_all": "完整清理",
        "uninstall_scope_registration": "仅取消注册",
        "uninstall_scope_files": "取消注册并删除托管 ~/.omh 文件",
        "uninstall_config": "Hermes 注册: {message}",
        "uninstall_removed": "已删除: {count} 个路径",
        "uninstall_would_remove": "将删除: {count} 个路径",
        "uninstall_none": "没有需要删除的项目。",
        "uninstall_command_removed": "命令包: 已删除 {count} 个 install.sh 托管路径。",
        "uninstall_command_would_remove": "命令包: 将删除 {count} 个 install.sh 托管路径。",
        "uninstall_command_kept": "命令包: 当前 `omh` 不是从 install.sh 托管的 OMH venv 运行，因此未删除。",
        "uninstall_command_still_available": "如果 uninstall 后 `omh` 仍可运行，说明命令包仍在 PATH 中；请从安装它的 installer-managed venv、pip 或 pipx 中删除。",
        "scope": "范围",
        "kept": "保留",
    },
}


def normalize_language(value: str | None) -> str:
    key = str(value or "").strip().lower()
    language = _LANGUAGE_ALIASES.get(key)
    if language:
        return language
    valid = ", ".join(LANGUAGE_CODES)
    raise ValueError(f"unsupported language: {value}; expected one of {valid}")


def language_from_env(default: str = "en") -> str:
    return normalize_language(os.environ.get("OMH_LANG") or os.environ.get("OMH_LANGUAGE") or default)


def language_options() -> list[dict[str, str]]:
    return [
        {"choice": str(index), "value": code, "label": LANGUAGE_NAMES[code], "description": ""}
        for index, code in enumerate(LANGUAGE_CODES, start=1)
    ]


def tr(language: str, key: str, **kwargs: object) -> str:
    code = normalize_language(language)
    template = MESSAGES.get(code, {}).get(key) or MESSAGES["en"][key]
    return template.format(**kwargs)
