from __future__ import annotations

from dataclasses import dataclass

from ..harness_quality import build_harness_quality_contract, unknown_harness_quality_contract


@dataclass(frozen=True)
class SkillDefinition:
    name: str
    description: str
    triggers: tuple[str, ...]
    use_when: str
    category: str = "workflow"
    phase: str = "general"
    hermes_role: str = "hybrid-guidance"
    delegation_boundary: str = "default"
    handoff_policy: str = "Use Hermes-native guidance directly; prepare a selected executor handoff only when the accepted request requires code edits."
    required_inputs: tuple[str, ...] = ("task statement", "available Hermes context")
    expected_outputs: tuple[str, ...] = ("workflow-shaped response", "verification or explicit gap")
    artifact_expectations: tuple[str, ...] = ("metadata-only runtime record when a wrapper or shell is available",)
    safety_rules: tuple[str, ...] = (
        "Do not imply hidden Hermes runtime behavior.",
        "Use the smallest verification that can prove the claim.",
    )
    quality_tier: str = "evidence-gated"
    quality_bar: tuple[str, ...] = (
        "Name the workflow target, constraints, validation evidence, and stop condition.",
        "Separate Hermes guidance from executor or wrapper behavior unless evidence proves the step happened.",
    )


@dataclass(frozen=True)
class HarnessDefinition:
    name: str
    purpose: str
    use_when: str
    required_inputs: tuple[str, ...]
    expected_outputs: tuple[str, ...]
    stop_conditions: tuple[str, ...]
    verification: tuple[str, ...]
    fallback: str
    artifact_events: tuple[str, ...]
    delegation_expectation: str
    privacy_default: str
    quality_tier: str = "evidence-gated"
    quality_bar: tuple[str, ...] = (
        "State the lane objective, required inputs, expected outputs, and stop condition before claiming completion.",
        "Record only metadata-safe evidence and leave unavailable delegation explicit.",
    )
    evidence_ladder: tuple[str, ...] = (
        "request_received",
        "lane_started",
        "evidence_recorded",
        "result_reported",
    )
    wrapper_actions: tuple[str, ...] = ("show_status",)
    overclaim_guards: tuple[str, ...] = (
        "Do not upgrade requested or prepared work into observed completion without runtime or wrapper evidence.",
    )


CODING_INTENTS = ("coding", "cleanup", "review", "planning", "diagnostics", "docs", "unknown")
CODING_INTENT_PRIORITY = ("cleanup", "review", "planning", "diagnostics", "docs", "coding")
CODING_INTENT_TERMS = {
    "cleanup": ("cleanup", "clean", "refactor", "deslop", "legacy", "리팩터링", "리팩토링", "레거시", "회귀 테스트"),
    "review": (
        "review",
        "audit",
        "critic",
        "critique",
        "release gate",
        "claim",
        "evidence boundary",
        "리뷰",
        "릴리즈 전",
        "릴리즈",
        "과장",
        "실제 코드",
        "실제로 뭐 했는지",
    ),
    "planning": (
        "plan",
        "planning",
        "strategy",
        "architecture",
        "design",
        "proposal",
        "triage",
        "issue to pr",
        "acceptance criteria",
        "verification command",
        "workflow",
        "pipeline",
        "handoff",
        "idea to deploy",
        "from idea to deploy",
        "plan to deploy",
        "cto loop",
        "roadmap",
        "launch",
        "deploy and monitor",
        "rollback",
        "계획",
        "기획",
        "조사",
        "재현 계획",
        "이슈",
        "pr로",
        "요구사항",
        "온보딩",
        "고객 피드백",
        "기능 요청",
        "고객사",
        "프로젝트별",
        "작업 허브",
        "상태와 다음 행동",
        "아이디어부터 배포",
        "기획부터 배포",
        "완제품 루프",
        "출시",
        "배포 모니터링",
        "롤백",
    ),
    "diagnostics": (
        "diagnose",
        "doctor",
        "debug",
        "health",
        "broken",
        "failing",
        "failure",
        "incident",
        "reproduce",
        "결제 실패",
        "실패",
        "버그",
        "장애",
        "진단",
        "재현",
    ),
    "docs": ("docs", "documentation", "readme", "guide", "wiki", "문서", "가이드", "운영자 가이드"),
    "coding": ("code", "implement", "build", "fix", "change", "modify", "add", "write", "구현", "수정", "추가", "변경", "고쳐", "만들"),
}
CODING_REVIEW_TERMS = (
    *CODING_INTENT_TERMS["review"],
    "risky",
    "risk",
    "migration",
    "security",
    "public api",
    "위험",
    "릴리즈",
)
_CODING_INTENT_BY_SKILL = {
    "ai-slop-cleaner": "cleanup",
    "code-review": "review",
    "plan": "planning",
    "ralplan": "planning",
    "research-brief": "planning",
    "strategy-brief": "planning",
    "meeting-brief": "planning",
    "feedback-triage": "planning",
    "ops-review": "planning",
    "idea-to-deploy": "planning",
    "cto-loop": "planning",
    "deploy-and-monitor": "planning",
    "loop": "planning",
    "ultraprocess": "planning",
    "best-practice-research": "planning",
    "web-research": "planning",
    "ultraqa": "diagnostics",
    "doctor": "diagnostics",
    "wiki": "docs",
}


_DEFINITIONS = [
    SkillDefinition(
        "oh-my-hermes",
        "Router guidance for using oh-my-hermes workflow skills inside Hermes Agent.",
        (
            "oh-my-hermes",
            "omh",
            "skill routing",
            "workflow routing",
            "chat routing",
            "request-to-handoff",
            "plain request",
            "role-owned next action",
            "wrapper contract",
            "prepared observed",
            "evidence boundary",
            "상태 기록",
            "증거 경계",
        ),
        "Use as the top-level router when a request references oh-my-hermes, the flagship request-to-handoff path, installed workflows, or ambiguous workflow routing.",
        category="router",
        phase="routing",
        hermes_role="retained-router",
        handoff_policy="Classify requests into Hermes-retained planning/research/interview lanes, executor choice, or prepared coding handoffs; do not execute code.",
        required_inputs=("user request", "installed skill descriptions", "Hermes skill discovery context"),
        expected_outputs=("selected workflow guidance", "clarification question when routing is ambiguous"),
        artifact_expectations=("runtime run record when a wrapper can observe request handling",),
        safety_rules=(
            "Prefer explicit skill invocation over weak keyword inference.",
            "Ask one concise question when routing signals conflict.",
            "Do not claim to override Hermes core routing.",
        ),
        quality_tier="routing-gated",
        quality_bar=(
            "Route only from explicit invocation, strong catalog evidence, or a clear workflow-shaped request.",
            "Return a clarification or fallback path instead of forcing low-confidence messages into a workflow.",
            "Keep users command-agnostic by naming the next UX step rather than shell commands.",
            "Use request-to-handoff as the first path when a plain request needs role, plan, handoff, or status UX.",
        ),
    ),
    SkillDefinition(
        "ralph",
        "Hermes Ralph workflow: persistent execution with verification and review.",
        ("ralph", "$ralph", "finish until done", "persistent execution", "self-referential loop"),
        "Use after scope is concrete and the user wants one owner to continue through implementation and verification.",
        category="execution",
        phase="completion",
        hermes_role="codex-handoff-guidance",
        handoff_policy="Keep as compatibility guidance; for implementation, ask the wrapper to prepare/track the selected executor path instead of making Hermes the hidden coder.",
        required_inputs=("concrete scope", "acceptance criteria", "verification commands"),
        expected_outputs=("completed work summary", "verification evidence", "remaining risks"),
        artifact_expectations=("goal-execution run record", "checkpoint or final evidence when available"),
        quality_tier="handoff-gated",
        quality_bar=(
            "Do not enter a finish-until-done loop until scope, acceptance criteria, and verification commands are concrete.",
            "For coding edits, prepare and track selected executor evidence instead of implying Hermes implemented the changes.",
            "Report completion only from observed execution and verification evidence.",
        ),
    ),
    SkillDefinition(
        "ultragoal",
        "Hermes Ultragoal workflow: file-backed durable goal ledgers.",
        ("ultragoal", "$ultragoal", "durable goal", "multi-goal", "goal ledger"),
        "Use when work needs durable goal artifacts, checkpointed progress, and final quality gates.",
        category="execution",
        phase="durable-goals",
        hermes_role="codex-handoff-guidance",
        handoff_policy="Use Hermes to maintain .omh/goals goal_ledger/v1 state, show goal_status_card/v1 / goal_continuation/v1 next actions, and delegate coding milestones to the selected executor with only observed runtime evidence.",
        required_inputs=("goal statement", "acceptance criteria", "current checkpoint or missing criteria"),
        expected_outputs=("goal_ledger/v1 updates", "checkpoint evidence", "goal_completion_gate/v1 result", "completion or blocker summary"),
        artifact_expectations=("metadata-only .omh/goals ledger", "goal_status_card/v1 or goal_continuation/v1 wrapper payload", "runtime run record only for explicitly linked coding milestones"),
        quality_tier="checkpoint-gated",
        quality_bar=(
            "Keep goal state durable, inspectable, and separate from chat narration.",
            "Checkpoint every success, blocker, and final quality gate with fresh evidence.",
            "Reject completion with a summary-only goal_completion_gate/v1 result until required criteria, blockers, and explicitly linked runtime runs are satisfied.",
            "Tell the user the next action through goal_status_card/v1 or goal_continuation/v1 instead of ending with vague follow-up copy.",
            "For coding milestones, use prepared handoffs and observed executor evidence rather than hidden Hermes execution.",
        ),
    ),
    SkillDefinition(
        "loop",
        "Hermes Loop workflow: ambitious goal interview, research, planning, runtime ticks, handoff, feedback, and resume cycles.",
        (
            "loop",
            "./loop",
            "$loop",
            "goal loop",
            "long horizon goal",
            "never stop",
            "research plan ultragoal feedback",
            "token exhaustion resume",
            "permission profile",
            "star 10k",
            "10k star",
            "loop engineering",
            "루프",
            "목표 루프",
            "장기 목표",
            "끝까지",
            "토큰 고갈",
            "피드백 루프",
        ),
        "Use when the user explicitly starts a high-level, long-horizon goal loop that should refine the goal, separate implementable work from external waiting, and keep cycling through task discovery, distribution, execution, verification, next-task decisions, runtime tick queueing, handoff, feedback, and status until the authority envelope or evidence gate stops it.",
        category="goal-loop",
        phase="continuous-goal-loop",
        hermes_role="retained-cognition",
        delegation_boundary="retained-catalog-intent",
        handoff_policy="Keep loop orchestration, interviews, research, planning, runtime ticks with deterministic queue shapes, loop_engineering/v1 pipeline and building-block status, feedback evaluation, status, and permission-envelope narration in Hermes; prepare selected executor/worktree/connector handoffs only when the loop produces concrete work and record completion only from linked goal/runtime evidence.",
        required_inputs=("north-star goal summary", "goal reframe", "success criteria", "permission profile", "feedback or wait signal"),
        expected_outputs=("loop_start_card/v1 setup prompt", "loop_cycle/v1 state", "loop_engineering/v1 pipeline/building-block snapshot", "loop cost_policy for bounded reads and verifier restraint", "loop_status_card/v1 next action", "loop_runtime/v1 queued tick with loop policy refs", "loop_queue_handoff/v1 only when permitted", "executor-neutral handoff only when permitted", "external-wait or checkpoint boundary"),
        artifact_expectations=("metadata-only .omh/loops loop_cycle/v1 artifact", "loop_engineering/v1 status over automation, worktree, skill, connector, and subagent blocks", "loop_runtime/v1 queue entries with context_policy_ref and cost_policy_ref", "loop_subagent_result_contract/v1 for prepared subagent handoffs", "loop_status_card/v1 wrapper payload", "loop_start_card/v1 wrapper setup card", "linked goal_ledger/v1 only when completion evidence is required"),
        safety_rules=(
            "Do not treat loop persistence as permission to bypass the selected permission profile.",
            "Do not treat a runtime tick as worktree creation, subagent dispatch, connector I/O, implementation, review, CI, merge, publication, or completion evidence.",
            "Do not claim goal completion from loop state; require linked goal_ledger/v1 completion evidence.",
            "When context or token budget runs out, checkpoint or rely on resumable state instead of pretending the loop is complete.",
            "External results such as market response, stars, or adoption are waiting states unless observed evidence is supplied.",
        ),
        quality_tier="loop-gated",
        quality_bar=(
            "Start with direct user intent such as `./loop` or an explicit ambitious goal loop request.",
            "Reframe the north-star goal into implementable internal work without shrinking its ambition.",
            "Separate task discovery, distribution, execution, verification, next-task decision, runtime tick queueing, ultragoal/handoff, feedback, waiting, and resume decisions.",
            "Expose a permission profile before executor dispatch, repository mutation, PR, merge, or external publishing.",
            "Expose the automation, worktree, skill, connector, and subagent building-block states without treating planned blocks as observed work.",
            "Choose workflow patterns such as single-step, fan-out-and-synthesize, adversarial verification, tournament, or triage batch as orchestration metadata only.",
            "Keep repeated scaffold shape stable, summarize within bounded budgets, and add verifier lanes only when risk or evidence warrants them.",
            "Keep prepared worktree/subagent/connector plans, observed executor work, linked goal completion, and external waiting as distinct evidence states.",
        ),
    ),
    SkillDefinition(
        "ultraprocess",
        "Ultra Process - Research - Ralplan - Ultragoal - Code Review - Sync Circle: one PR-ready delivery cycle.",
        (
            "ultraprocess",
            "$ultraprocess",
            "./ultraprocess",
            "/ultraprocess",
            "single-cycle delivery",
            "one-cycle delivery",
            "end-to-end process",
            "delivery process",
            "research plan implement review docs pr",
            "plan implement review docs pr",
            "ralplan ultragoal code-review",
            "codebase research web research planning implementation review docs sync pr",
            "docs sync",
            "pr-ready",
            "prepare a pr",
            "sync docs and prepare a pr",
            "code-review sync docs and prepare a pr",
            "make a pr",
            "open a pr",
            "끝까지 해줘",
            "PR까지",
            "계획 구현 리뷰 문서 PR",
            "기획 구현 리뷰 문서 PR",
            "코드베이스 조사 웹리서치 계획 구현 리뷰 문서 최신화 PR",
            "문서 최신화 PR",
        ),
        "Use when the user asks Hermes to take a concrete task through one full delivery cycle: research/codebase context, reviewed plan, selected implementation handoff, code review, docs sync when needed, and PR preparation.",
        category="process",
        phase="single-cycle-plan-to-pr",
        hermes_role="retained-cognition",
        delegation_boundary="retained-catalog-intent",
        handoff_policy="Keep the one-cycle process orchestration, source/codebase research, planning, review framing, docs-sync checks, PR narration, and evidence boundaries in Hermes; convert implementation into a selected executor handoff such as Codex, Claude Code, another coding agent, or explicit Hermes-retained work only when the user accepts that owner.",
        required_inputs=("task statement", "repo or workspace context", "executor preference or choose-at-handoff policy", "verification expectations"),
        expected_outputs=("ralplan-ready context and plan", "ultragoal or selected executor handoff", "code-review gate", "docs sync checklist", "single-cycle PR-ready summary with observed evidence and gaps"),
        artifact_expectations=("process checklist or runtime record when a wrapper can observe the stages", "prepared handoff artifact only after implementation owner selection", "docs-specialist claim check when public behavior changes"),
        safety_rules=(
            "Do not skip planning when the request is broad, risky, or user-visible.",
            "Do not continue into a repeated feedback loop; recommend `loop` when the user wants ongoing cycles.",
            "Do not claim implementation, review, CI, merge readiness, or PR creation without observed executor or GitHub evidence.",
            "Keep web research source-backed and permission-aware; do not run hidden network or LLM calls from OMH core.",
            "Run docs sync only when behavior, setup, commands, or public claims changed.",
        ),
        quality_tier="process-gated",
        quality_bar=(
            "Complete exactly one plan-to-PR delivery cycle, then stop with status, evidence gaps, or a next recommended workflow.",
            "Start with codebase/source research and a ralplan-style decision record before implementation handoff.",
            "Use ultragoal or the selected executor path for implementation, with acceptance criteria and verification commands attached.",
            "Run code-review as a gate after implementation evidence exists; review preparation alone is not review evidence.",
            "Add docs-specialist sync when public behavior, commands, setup, examples, or claims changed.",
            "End with a PR-ready or PR-observed report that separates prepared, executed, reviewed, verified, CI, and PR evidence.",
        ),
    ),
    SkillDefinition(
        "deep-interview",
        "Hermes Deep Interview workflow: one-question-at-a-time clarification.",
        (
            "deep-interview",
            "$deep-interview",
            "interview",
            "don't assume",
            "clarify",
            "feature shaping",
            "ambiguous product request",
            "one question",
            "온보딩",
            "부드럽게",
            "모호한 제품 요청",
            "기획자",
            "개발자 사이",
        ),
        "Use before planning or execution when requirements are materially ambiguous.",
        category="clarification",
        phase="discovery",
        hermes_role="retained-cognition",
        delegation_boundary="retained",
        handoff_policy="Run directly in Hermes or the chat wrapper; produce a clarified brief before any coding handoff is prepared.",
        required_inputs=("initial request", "known repo facts", "current ambiguity"),
        expected_outputs=("clarified brief", "non-goals", "decision boundaries"),
        artifact_expectations=("clarity summary or transcript when the wrapper supports it",),
        safety_rules=(
            "Ask one question at a time.",
            "Gather discoverable repo facts before asking the user.",
            "Stop interviewing once ambiguity is low enough to plan.",
        ),
        quality_tier="clarity-gated",
        quality_bar=(
            "Ask exactly one blocking question per turn unless the wrapper explicitly supports a structured batch.",
            "Tie each question to a missing decision that changes the plan, handoff, or stop condition.",
            "Emit a clarified brief with non-goals and acceptance criteria before planning or delegation.",
        ),
    ),
    SkillDefinition(
        "team",
        "Hermes Team workflow: coordinated parallel or sequential work lanes.",
        ("team", "$team", "swarm", "parallel agents", "coordinated workers"),
        "Use when multiple independent lanes materially improve throughput or verification.",
        category="execution",
        phase="coordination",
        hermes_role="codex-handoff-guidance",
        handoff_policy="Use Hermes for lane framing and status; implementation lanes should become selected executor handoff tasks unless they are research, interview, planning, or status-only.",
        required_inputs=("bounded lane definitions", "ownership boundaries", "verification target"),
        expected_outputs=("lane results", "integration summary", "combined verification evidence"),
        artifact_expectations=("delegation record only when separate participants are observed",),
        safety_rules=(
            "Use parallel lanes only when work is independent.",
            "Keep shared-file edits under one owner.",
            "Record unobserved delegation as not_observed.",
        ),
        quality_tier="coordination-gated",
        quality_bar=(
            "Split only independent lanes with explicit ownership and verification boundaries.",
            "Keep Hermes as coordinator and status narrator while coding lanes become executor handoffs.",
            "Integrate lane evidence before reporting combined progress.",
        ),
    ),
    SkillDefinition(
        "ultrawork",
        "Hermes Ultrawork compatibility workflow: bounded parallel delivery guidance.",
        ("ultrawork", "$ultrawork", "parallel work", "parallel implementation", "high throughput"),
        "Use when an accepted implementation plan can be split into independent, reviewable work lanes.",
        category="execution",
        phase="parallel-delivery",
        hermes_role="codex-handoff-guidance",
        handoff_policy="Keep the workflow name for compatibility, but convert coding lanes into explicit selected executor handoffs with disjoint scope, verification, and review evidence.",
        required_inputs=("accepted plan", "lane list", "disjoint file or responsibility scopes", "verification commands"),
        expected_outputs=("executor handoff prompts or lane instructions", "status summary", "review/CI evidence requirements"),
        artifact_expectations=("prepared coding delegation record per implementation lane when wrappers can record them",),
        safety_rules=(
            "Do not start parallel coding without disjoint ownership boundaries.",
            "Keep Hermes responsible for orchestration/status, not hidden implementation.",
            "Record unobserved executor work as prepared_not_observed or not_observed.",
        ),
        quality_tier="handoff-gated",
        quality_bar=(
            "Require disjoint lane ownership before preparing multiple coding handoffs.",
            "Attach acceptance criteria, verification commands, and review expectations to each lane.",
            "Keep dispatch, execution, review, CI, and merge status evidence separate.",
        ),
    ),
    SkillDefinition(
        "web-research",
        "Hermes Web Research workflow: source-backed current information gathering.",
        (
            "web-research",
            "web research",
            "latest",
            "current sources",
            "source-backed research",
            "investigate",
            "research plan",
            "조사",
            "근거",
            "출처",
            "고객 피드백",
        ),
        "Use when the user needs current web evidence, links, citations, or source comparison before planning or handoff.",
        category="research",
        phase="current-evidence",
        hermes_role="retained-cognition",
        delegation_boundary="retained",
        handoff_policy="Run as a Hermes-side research lane when web access is available; summarize evidence before any coding handoff and never treat research as implementation.",
        required_inputs=("research question", "source boundaries", "recency or jurisdiction constraints"),
        expected_outputs=("source-backed synthesis", "links or citations", "confidence and residual uncertainty"),
        artifact_expectations=("research notes with source URLs when the wrapper captures them",),
        safety_rules=(
            "Prefer official or primary sources when they can answer the question.",
            "Separate quoted evidence from inference.",
            "State retrieval limits and dates for unstable facts.",
        ),
        quality_tier="source-gated",
        quality_bar=(
            "Use official or primary sources first when current or external facts matter.",
            "Separate direct evidence, inference, confidence, and residual uncertainty.",
            "Summarize research before any coding handoff; research is not implementation evidence.",
        ),
    ),
    SkillDefinition(
        "research-brief",
        "Hermes Research Brief workflow: source-backed business research without pretending evidence was fetched.",
        (
            "research-brief",
            "business-research",
            "business research",
            "research brief",
            "source-backed business research",
            "customer feedback trends",
            "feedback trends",
            "market evidence",
            "data search",
            "source scan",
            "자료 조사",
            "데이터 서치",
            "근거 조사",
            "피드백 추세",
            "고객 피드백 추세",
        ),
        "Use when Hermes should scope a business question, gather or summarize source-backed evidence, and preserve evidence/inference boundaries before strategy or handoff.",
        category="research",
        phase="business-brief",
        hermes_role="retained-cognition",
        delegation_boundary="retained-catalog-intent",
        handoff_policy="Keep business research in Hermes; prepare a selected executor handoff only after a later accepted plan requires code changes.",
        required_inputs=("business question", "source boundary", "recency or market scope"),
        expected_outputs=("evidence table", "inference summary", "confidence and uncertainty"),
        artifact_expectations=("research brief or source ledger when the wrapper captures observed sources",),
        safety_rules=(
            "Do not claim sources were fetched unless Hermes or the wrapper observed them.",
            "Separate evidence, inference, confidence, and missing-source gaps.",
            "Route later implementation separately through an accepted plan and coding handoff.",
        ),
        quality_tier="source-gated",
        quality_bar=(
            "State the research question, source boundaries, and recency assumptions before synthesis.",
            "Separate observed sources from inferred trends and unresolved uncertainty.",
            "Use the brief to feed strategy or meeting work without calling it execution evidence.",
        ),
    ),
    SkillDefinition(
        "strategy-brief",
        "Hermes Strategy Brief workflow: options, tradeoffs, recommendation, and decision notes.",
        (
            "strategy-brief",
            "strategy brief",
            "strategy memo",
            "product strategy",
            "strategic options",
            "decision note",
            "leadership strategy",
            "next strategy",
            "다음 전략",
            "전략 정리",
            "전략 메모",
            "전략 옵션",
            "의사결정",
            "리더십 회의",
        ),
        "Use when Hermes should turn goals and evidence into options, tradeoffs, recommendations, and a decision-ready brief.",
        category="strategy",
        phase="brief",
        hermes_role="retained-cognition",
        delegation_boundary="retained-catalog-intent",
        handoff_policy="Keep strategy synthesis in Hermes; do not create implementation handoff until a decision is accepted and code work is explicit.",
        required_inputs=("goal", "known evidence", "constraints", "decision owner"),
        expected_outputs=("options", "tradeoffs", "recommended direction", "decision note"),
        artifact_expectations=("strategy brief or decision note when a wrapper captures it",),
        safety_rules=(
            "Do not treat a draft recommendation as an accepted decision.",
            "Keep unresolved assumptions visible.",
            "Separate strategy from implementation planning unless the user asks for execution.",
        ),
        quality_tier="decision-gated",
        quality_bar=(
            "Name the decision, constraints, options, tradeoffs, and rejected alternatives.",
            "Tie recommendations to observed evidence or mark them as assumptions.",
            "Keep coding handoff disabled until strategy is accepted and code work is explicit.",
        ),
    ),
    SkillDefinition(
        "meeting-brief",
        "Hermes Meeting Brief workflow: agenda, prompts, decisions, and record template.",
        (
            "meeting-brief",
            "meeting brief",
            "meeting agenda",
            "agenda",
            "discussion prompts",
            "decisions needed",
            "record template",
            "meeting topics",
            "회의 주제",
            "회의 아젠다",
            "아젠다",
            "회의 준비",
            "논의 질문",
            "결정할 것",
            "기록 템플릿",
        ),
        "Use when Hermes should prepare a meeting agenda, discussion prompts, decision points, and a record template.",
        category="meeting",
        phase="preparation",
        hermes_role="retained-cognition",
        delegation_boundary="retained-catalog-intent",
        handoff_policy="Run meeting preparation in Hermes; only create follow-up coding handoff from observed decisions or accepted plans.",
        required_inputs=("meeting goal", "audience", "known context", "decision topics"),
        expected_outputs=("agenda", "discussion prompts", "decisions needed", "action-item template"),
        artifact_expectations=("meeting brief or record template when the wrapper captures it",),
        safety_rules=(
            "Do not claim the meeting happened from a prepared agenda.",
            "Separate proposed action items from observed decisions.",
            "Use a later status or decision record for actual meeting outcomes.",
        ),
        quality_tier="facilitation-gated",
        quality_bar=(
            "Turn context into agenda topics, prompts, decisions needed, and a record template.",
            "Keep prep distinct from actual meeting minutes or accepted decisions.",
            "Identify missing context that would change the meeting structure.",
        ),
    ),
    SkillDefinition(
        "feedback-triage",
        "Hermes Feedback Triage workflow: cluster customer signals and choose the next workflow.",
        (
            "feedback-triage",
            "customer-feedback-triage",
            "feedback triage",
            "customer feedback",
            "feedback cluster",
            "bug or feature",
            "feature request triage",
            "payment failure feedback",
            "feedback trends",
            "고객 피드백",
            "피드백",
            "피드백 분류",
            "피드백을 모아서",
            "결제 실패 피드백",
            "버그 기능 요청",
            "기능 요청",
        ),
        "Use when Hermes should classify feedback, bug reports, and feature asks before deciding whether research, planning, or coding handoff is needed.",
        category="triage",
        phase="feedback",
        hermes_role="retained-cognition",
        delegation_boundary="retained-catalog-intent",
        handoff_policy="Keep feedback triage in Hermes; recommend the next workflow and prepare a selected executor handoff only after explicit coding intent or accepted plan evidence.",
        required_inputs=("feedback items or summary", "source boundary", "product area"),
        expected_outputs=("clusters", "severity or opportunity ranking", "next workflow recommendation"),
        artifact_expectations=("feedback triage record when a wrapper captures it",),
        safety_rules=(
            "Do not turn feedback into a roadmap, implementation plan, or coding handoff by default.",
            "Separate bug signal, feature ask, severity, opportunity, and missing evidence.",
            "Route code changes only after explicit user intent or accepted planning evidence.",
        ),
        quality_tier="triage-gated",
        quality_bar=(
            "Name the source boundary before clustering feedback.",
            "Classify signals into bug, feature, research, or strategy follow-up without overclaiming evidence.",
            "Recommend the next workflow instead of jumping straight to coding.",
        ),
    ),
    SkillDefinition(
        "ops-review",
        "Hermes Ops Review workflow: status, risks, blockers, priorities, and follow-ups.",
        (
            "ops-review",
            "ops review",
            "weekly ops review",
            "status review",
            "operating review",
            "release risks",
            "risks and blockers",
            "priorities",
            "weekly status",
            "운영 리뷰",
            "주간 운영",
            "상태 리뷰",
            "리스크",
            "블로커",
            "우선순위",
            "릴리즈 리스크",
        ),
        "Use when Hermes should summarize observed status, risks, blockers, priorities, and follow-up actions for recurring operating work.",
        category="operations",
        phase="status-review",
        hermes_role="retained-cognition",
        delegation_boundary="retained-catalog-intent",
        handoff_policy="Keep operating review and status narration in Hermes; delegate code fixes only from explicit accepted follow-up items.",
        required_inputs=("status evidence", "scope", "time window", "known risks"),
        expected_outputs=("status summary", "risks", "blockers", "priorities", "follow-up actions"),
        artifact_expectations=("ops review record or status artifact when a wrapper captures it",),
        safety_rules=(
            "Do not infer status from missing evidence.",
            "Separate observed facts, risks, blockers, decisions, and follow-up actions.",
            "Do not report review, CI, release, or merge readiness from an ops summary alone.",
        ),
        quality_tier="status-gated",
        quality_bar=(
            "Tie every status claim to observed evidence or mark it as unknown.",
            "Separate risks, blockers, priorities, and follow-up owners.",
            "Keep code fixes as explicit follow-up handoffs, not implicit ops-review output.",
        ),
    ),
    SkillDefinition(
        "idea-to-deploy",
        "Hermes Idea-to-Deploy workflow: shape an app idea into decisions, delivery handoff, verification, release, and monitoring status.",
        (
            "idea-to-deploy",
            "idea to deploy",
            "from idea to deploy",
            "plan to deploy",
            "idea to launch",
            "ship this idea",
            "ship this feature",
            "launch this feature",
            "product delivery loop",
            "app delivery loop",
            "complete product loop",
            "end-to-end app operation",
            "완제품 루프",
            "아이디어부터 배포",
            "기획부터 배포",
            "출시까지",
            "앱 운영 루프",
        ),
        "Use when Hermes should carry a product or app idea through shaping, decision gates, plan acceptance, executor handoff, verification, release readiness, deploy, and monitoring boundaries.",
        category="delivery",
        phase="app-delivery-loop",
        hermes_role="retained-cognition",
        delegation_boundary="retained-catalog-intent",
        handoff_policy="Keep idea shaping, decision gates, planning, release narration, and status in Hermes; prepare selected executor handoffs only for accepted code work and record deploy/monitoring only from observed operator or wrapper evidence.",
        required_inputs=("product idea", "target user or customer signal", "success metric", "repo or app context"),
        expected_outputs=("stage rail", "decision gates", "executor handoff criteria", "verification and deploy/monitor status boundaries"),
        artifact_expectations=("app delivery loop status record when the wrapper captures stage acceptance or observations",),
        safety_rules=(
            "Do not claim implementation, deploy, health checks, rollback, or monitoring happened from a prepared loop.",
            "Keep coding, release, and monitoring observations as separate evidence gates.",
            "Ask for missing success metric, release scope, or executor choice before preparing a handoff.",
        ),
        quality_tier="delivery-gated",
        quality_bar=(
            "Name the idea, user value, decision owner, non-goals, and success metric before planning delivery.",
            "Expose idea, decision, plan, handoff, verification, release, deploy, and monitor stages as separate status steps.",
            "Prepare coding handoffs only after plan acceptance and selected executor choice.",
            "Mark deploy, monitoring, and rollback as unobserved until the wrapper or operator records evidence.",
        ),
    ),
    SkillDefinition(
        "cto-loop",
        "Hermes CTO Loop workflow: roadmap, PM, technical tradeoffs, risk, delivery, release, and follow-up operating cadence.",
        (
            "cto-loop",
            "cto loop",
            "cto",
            "cto pm",
            "pm dev qa security ops",
            "roadmap technical tradeoffs",
            "technical tradeoff",
            "delivery risk",
            "release readiness",
            "technical leadership loop",
            "leadership operating loop",
            "engineering leadership",
            "CTO 구조",
            "PM 구조",
            "로드맵",
            "아키텍처 트레이드오프",
            "기술 리더십",
            "출시 준비",
        ),
        "Use when Hermes should run a leadership-style operating loop that turns signals into roadmap decisions, technical tradeoffs, delivery risk, release readiness, and explicit follow-up handoffs.",
        category="leadership",
        phase="operating-loop",
        hermes_role="retained-cognition",
        delegation_boundary="retained-catalog-intent",
        handoff_policy="Keep CTO/PM-style synthesis, tradeoffs, risk ranking, decision notes, and status in Hermes; convert accepted implementation follow-ups into executor-neutral handoffs.",
        required_inputs=("operating signals", "roadmap or release scope", "known risks", "decision owner"),
        expected_outputs=("priority frame", "architecture tradeoffs", "delivery risks", "decision note", "follow-up handoff candidates"),
        artifact_expectations=("leadership loop record or status summary when a wrapper captures decisions and follow-ups",),
        safety_rules=(
            "Do not treat a CTO loop recommendation as an accepted roadmap decision.",
            "Do not imply CTO, PM, QA, Security, or Ops runtime agents exist without observed wrapper evidence.",
            "Separate strategy decisions from implementation handoffs and release evidence.",
        ),
        quality_tier="decision-gated",
        quality_bar=(
            "Separate product priority, architecture tradeoff, delivery risk, release risk, and follow-up owner.",
            "Tie recommendations to observed signals or mark assumptions.",
            "Record accepted decisions separately from draft recommendations.",
            "Prepare executor handoffs only for accepted implementation follow-ups.",
        ),
    ),
    SkillDefinition(
        "deploy-and-monitor",
        "Hermes Deploy-and-Monitor workflow: release checklist, deploy decision, health signals, rollback gate, and post-deploy status.",
        (
            "deploy-and-monitor",
            "deploy and monitor",
            "deploy monitor",
            "deployment monitoring",
            "release monitor",
            "post deploy",
            "post-deploy",
            "rollback",
            "rollback gate",
            "health check",
            "incident watch",
            "release health",
            "배포 모니터링",
            "배포 감시",
            "롤백",
            "헬스 체크",
            "장애 감시",
            "릴리즈 모니터링",
        ),
        "Use when Hermes should prepare or narrate a release operation with deploy checklist, health signals, rollback criteria, and post-deploy status without pretending to run infrastructure.",
        category="monitoring",
        phase="release-ops",
        hermes_role="retained-cognition",
        delegation_boundary="retained-catalog-intent",
        handoff_policy="Keep release checklist, health criteria, rollback gates, and status narration in Hermes; record deploy, monitor, incident, or rollback evidence only when the wrapper or operator observes it.",
        required_inputs=("release scope", "environment", "health signals", "rollback owner"),
        expected_outputs=("pre-deploy checklist", "deploy decision gate", "monitoring watchlist", "rollback criteria", "post-deploy status boundary"),
        artifact_expectations=("release operation status record when the wrapper captures deploy or monitor observations",),
        safety_rules=(
            "Do not claim deployment, health checks, rollback, or incident response happened from a prepared checklist.",
            "Keep release readiness, deploy decision, monitor signals, and rollback as separate evidence steps.",
            "Route code fixes discovered during monitoring as later executor handoffs.",
        ),
        quality_tier="release-gated",
        quality_bar=(
            "Name release scope, target environment, health signals, rollback criteria, and evidence owner.",
            "Show pre-deploy, deploy decision, monitor, rollback, and post-deploy record as distinct stages.",
            "Mark health and rollback status unknown until observed evidence arrives.",
            "Convert fix follow-ups into separate accepted plans or executor handoffs.",
        ),
    ),
    SkillDefinition(
        "ultraqa",
        "Hermes UltraQA workflow: adversarial QA and fix loops.",
        (
            "ultraqa",
            "$ultraqa",
            "adversarial qa",
            "hostile scenarios",
            "e2e qa",
            "real-world qa",
            "qa scenario",
            "release qa",
            "장애 상황",
            "쿠버네티스 장애",
            "적절히 진단",
            "검증 체크리스트",
            "릴리즈 전 gate",
        ),
        "Use when the task needs adversarial test scenarios, verification, and fix loops.",
        category="verification",
        phase="qa",
        hermes_role="hybrid-verification",
        delegation_boundary="retained",
        handoff_policy="Hermes can design scenarios and report observed results; code fixes discovered by QA should become selected executor handoffs.",
        required_inputs=("changed behavior", "acceptance criteria", "known risk areas"),
        expected_outputs=("adversarial scenarios", "pass/fail evidence", "fix recommendations"),
        artifact_expectations=("QA scenario evidence", "runtime verification summary"),
        quality_tier="scenario-gated",
        quality_bar=(
            "Generate hostile scenarios from changed behavior and known risk areas.",
            "Report pass/fail evidence separately from proposed fixes.",
            "Delegate code mutations discovered by QA to the selected coding executor.",
        ),
    ),
    SkillDefinition(
        "plan",
        "Hermes Plan workflow: structured planning before execution.",
        (
            "plan",
            "$plan",
            "implementation plan",
            "strategy",
            "task breakdown",
            "safe feature",
            "safely add a feature",
            "add a feature",
            "feature request",
            "new feature",
            "product triage",
            "bug triage",
            "issue triage",
            "reproduction plan",
            "workflow hub",
            "coding handoff",
            "답할 차례",
            "준비할 차례",
            "project template",
            "결제 실패",
            "결제 실패 이슈",
            "재현 계획",
            "고객 피드백",
            "기능 요청",
            "요구사항 정리",
            "작업 허브",
            "작업 허브가 필요",
            "github pr workflow",
            "상태와 다음 행동",
            "프로젝트별 운영",
        ),
        "Use for structured planning when implementation is not ready to start safely, including feature work that needs a safe plan before handoff.",
        category="planning",
        phase="plan",
        hermes_role="retained-cognition",
        handoff_policy="Keep planning in Hermes; if the accepted plan requires code edits, prepare a selected executor handoff after acceptance.",
        required_inputs=("requirements", "constraints", "known facts", "non-goals"),
        expected_outputs=("plan", "acceptance criteria", "verification strategy"),
        artifact_expectations=("plan artifact when durable execution will follow",),
        quality_tier="acceptance-gated",
        quality_bar=(
            "Make goals, non-goals, risks, acceptance criteria, and verification shape explicit.",
            "Keep draft plans unapproved until a user or wrapper accepts them.",
            "Only prepare coding handoff guidance after the plan is accepted.",
        ),
    ),
    SkillDefinition(
        "ralplan",
        "Hermes Ralplan workflow: consensus planning with review gates.",
        (
            "ralplan",
            "$ralplan",
            "consensus plan",
            "reviewed plan",
            "issue to PR",
            "acceptance criteria",
            "verification command",
            "reviewable PR",
            "PR로 만들",
            "PR로 만들 수 있게",
            "검증 command",
            "리뷰 가능한 단위",
        ),
        "Use when requirements are clear enough for planning but architecture, risks, or tests need review.",
        category="planning",
        phase="reviewed-plan",
        hermes_role="retained-cognition",
        handoff_policy="Keep consensus planning and review in Hermes; produce explicit selected executor handoff guidance only after the plan is accepted.",
        required_inputs=("requirements", "options", "tradeoffs", "test shape"),
        expected_outputs=("approved plan", "risk review", "handoff guidance"),
        artifact_expectations=("plan and review artifacts when a wrapper supports file-backed planning",),
        safety_rules=(
            "Do not implement directly from the planning lane.",
            "Make acceptance criteria testable.",
            "Record unresolved tradeoffs explicitly.",
        ),
        quality_tier="reviewed-plan-gated",
        quality_bar=(
            "Include a planner view, risk review, and testability check before handoff.",
            "Record unresolved tradeoffs and rejected options instead of flattening uncertainty.",
            "Do not implement directly from consensus planning.",
        ),
    ),
    SkillDefinition(
        "code-review",
        "Hermes Code Review workflow: bug-first review with evidence.",
        (
            "code-review",
            "$code-review",
            "review",
            "audit",
            "find bugs",
            "release gate",
            "claim audit",
            "evidence audit",
            "README claim",
            "what actually happened",
            "릴리즈 전",
            "실제 코드와 맞는가",
            "실제로 뭐 했는지",
            "검증된 결과",
        ),
        "Use for review-shaped requests; findings come first and must cite concrete evidence.",
        category="review",
        phase="critique",
        hermes_role="hybrid-review",
        handoff_policy="Hermes may frame and summarize review evidence; fixes or code mutations found during review should be delegated to the selected coding executor.",
        required_inputs=("diff or files", "expected behavior", "test evidence"),
        expected_outputs=("ranked findings", "open questions", "test gaps"),
        artifact_expectations=("critic run record when review evidence is captured",),
        safety_rules=(
            "Findings come before summaries.",
            "Cite concrete evidence for every finding.",
            "Say clearly when no issue is found.",
        ),
        quality_tier="finding-evidence-gated",
        quality_bar=(
            "Lead with ranked findings grounded in file, diff, command, or artifact evidence.",
            "Separate review findings from fix implementation; fixes become executor work.",
            "Say clearly when no actionable issue is found and name remaining test gaps.",
        ),
    ),
    SkillDefinition(
        "ai-slop-cleaner",
        "Hermes AI slop cleaner workflow: behavior-preserving cleanup.",
        (
            "ai-slop-cleaner",
            "$ai-slop-cleaner",
            "cleanup",
            "deslop",
            "refactor",
            "risky",
            "safe refactor",
            "risk analysis",
            "refactor workflow",
            "legacy refactor",
            "위험한 리팩터링",
            "리팩터링",
            "리팩토링",
            "위험 분석",
            "변경 범위 제한",
            "회귀 테스트",
        ),
        "Use for behavior-preserving cleanup with tests before and after edits.",
        category="maintenance",
        phase="cleanup",
        hermes_role="codex-handoff-guidance",
        handoff_policy="Use Hermes to define cleanup scope and regression checks; delegate behavior-preserving edits to the selected coding executor once tests are clear.",
        required_inputs=("target smell", "current behavior", "regression checks"),
        expected_outputs=("small cleanup diff", "before/after verification", "residual risk"),
        artifact_expectations=("cleanup plan and regression evidence for non-trivial work",),
        safety_rules=(
            "Lock behavior with tests before risky cleanup.",
            "Prefer deletion and existing utilities over new layers.",
            "Do not add dependencies for cleanup unless explicitly requested.",
        ),
        quality_tier="regression-gated",
        quality_bar=(
            "Lock current behavior with regression checks before non-trivial cleanup.",
            "Prefer deletion, reuse, and boundary repair over new abstractions.",
            "Rerun verification after cleanup before claiming behavior is preserved.",
        ),
    ),
    SkillDefinition(
        "best-practice-research",
        "Hermes adaptation for bounded official/upstream best-practice research.",
        ("best-practice-research", "best practice", "official docs", "upstream guidance"),
        "Use when correctness depends on current official or upstream guidance.",
        category="research",
        phase="evidence",
        hermes_role="retained-cognition",
        delegation_boundary="retained",
        handoff_policy="Run as Hermes-side evidence gathering; hand coding to the selected executor only after source-backed guidance is summarized.",
        required_inputs=("chosen technology", "question", "version or environment constraints"),
        expected_outputs=("source-backed guidance", "applicability notes", "residual uncertainty"),
        artifact_expectations=("research notes or citations when the wrapper captures them",),
        quality_tier="source-gated",
        quality_bar=(
            "Use official or upstream sources first and name the version/environment assumptions.",
            "Map applicability to the user's local context before recommending action.",
            "Preserve residual uncertainty instead of overstating best practice.",
        ),
    ),
    SkillDefinition(
        "autoresearch-goal",
        "Hermes adaptation for durable research-goal execution.",
        ("autoresearch-goal", "research goal", "durable research", "critic research"),
        "Use for validator-gated research that needs durable artifacts.",
        category="research",
        phase="durable-research",
        hermes_role="retained-cognition",
        delegation_boundary="retained",
        handoff_policy="Keep durable research in Hermes-managed artifacts; do not convert to executor handoff unless the research produces an accepted coding task.",
        required_inputs=("research objective", "validator criteria", "source boundaries"),
        expected_outputs=("research artifact", "validator result", "next questions"),
        artifact_expectations=("durable research ledger or checklist",),
        quality_tier="validator-gated",
        quality_bar=(
            "Define validator criteria before gathering evidence.",
            "Keep durable research artifacts separate from coding execution evidence.",
            "Stop with next questions or a source-backed synthesis when validation is incomplete.",
        ),
    ),
    SkillDefinition(
        "performance-goal",
        "Hermes adaptation for measurable performance-goal execution.",
        ("performance-goal", "performance goal", "latency", "throughput", "benchmark"),
        "Use when the goal is measurable performance improvement with evaluator evidence.",
        category="optimization",
        phase="measurement",
        hermes_role="hybrid-measurement",
        handoff_policy="Hermes can own baselines, benchmark plans, and status; optimization code changes should be selected executor handoffs.",
        required_inputs=("metric", "baseline", "budget", "benchmark command"),
        expected_outputs=("measurement delta", "implementation summary", "benchmark evidence"),
        artifact_expectations=("baseline and final benchmark evidence",),
        quality_tier="measurement-gated",
        quality_bar=(
            "Name the metric, baseline, budget, and benchmark command before optimizing.",
            "Treat code-level optimization as executor work when edits are required.",
            "Report deltas only from observed benchmark evidence.",
        ),
    ),
    SkillDefinition(
        "wiki",
        "Hermes adaptation for maintaining a project-local markdown wiki.",
        ("wiki", "project wiki", "memory", "notes"),
        "Use to capture durable project knowledge in markdown artifacts.",
        category="knowledge",
        phase="capture",
        hermes_role="retained-knowledge",
        delegation_boundary="retained",
        handoff_policy="Run directly in Hermes as knowledge capture unless the note reveals a separate coding task.",
        required_inputs=("project fact", "source evidence", "target topic"),
        expected_outputs=("markdown note", "retrieval hint", "staleness warning when needed"),
        artifact_expectations=("repo-local markdown knowledge artifact",),
        quality_tier="knowledge-gated",
        quality_bar=(
            "Capture durable facts with source evidence and retrieval hints.",
            "Mark stale or uncertain knowledge instead of presenting it as permanent truth.",
            "Extract separate coding tasks instead of burying them in notes.",
        ),
    ),
    SkillDefinition(
        "ask",
        "Hermes adaptation for consulting an external advisor when configured.",
        ("ask", "$ask", "external advisor", "claude", "gemini"),
        "Use only when an external advisor is configured and would materially improve the answer.",
        category="review",
        phase="external-advice",
        hermes_role="hybrid-review",
        handoff_policy="Use as optional advice gathering; evaluate the advice in Hermes and delegate coding changes separately.",
        required_inputs=("question", "context summary", "why external advice helps"),
        expected_outputs=("advisor summary", "accepted/rejected advice", "decision note"),
        artifact_expectations=("advisor transcript reference only when explicitly captured",),
        safety_rules=(
            "Use only when configured and materially useful.",
            "Treat advisor output as evidence to evaluate, not authority.",
            "Do not send secrets or private prompts without explicit opt-in.",
        ),
    ),
    SkillDefinition(
        "cancel",
        "Hermes adaptation for ending active workflow state cleanly.",
        ("cancel", "$cancel", "stop", "abort"),
        "Use to cleanly end active adapted workflow state.",
        category="operator",
        phase="state-cleanup",
        hermes_role="retained-operator",
        delegation_boundary="retained",
        handoff_policy="Run directly in Hermes/runtime state; never delegate cancellation to a coding executor.",
        required_inputs=("active workflow state", "cancellation intent"),
        expected_outputs=("cleared state", "safe stop summary"),
        artifact_expectations=("state clear record when state exists",),
    ),
    SkillDefinition(
        "skill",
        "Hermes adaptation for managing local skills.",
        ("skill", "$skill", "skills", "manage skills"),
        "Use for local skill listing, search, add, remove, or edit tasks.",
        category="operator",
        phase="skill-management",
        hermes_role="retained-operator",
        delegation_boundary="retained",
        handoff_policy="Use Hermes for inventory and guidance; delegate only repository code changes to the selected coding executor.",
        required_inputs=("skill action", "target skill name or directory"),
        expected_outputs=("skill inventory or mutation result", "verification note"),
        artifact_expectations=("manifest update when managed skills change",),
    ),
    SkillDefinition(
        "doctor",
        "Hermes adaptation for diagnosing oh-my-hermes installation health.",
        ("doctor", "$doctor", "diagnose omh", "installation health"),
        "Use to diagnose OMH installation and Hermes config registration.",
        category="operator",
        phase="diagnostics",
        hermes_role="retained-operator",
        handoff_policy="Run directly as local health inspection; propose executor work only when a repo fix is required.",
        required_inputs=("omh home", "Hermes home", "observed issue"),
        expected_outputs=("health checks", "fix guidance", "known proof boundary"),
        artifact_expectations=("doctor state summary when runtime artifacts are writable",),
    ),
]


_HARNESSES = [
    HarnessDefinition(
        "coding-handling",
        "Route implementation requests through scoped context, edit discipline, tests, review, and evidence.",
        "Use when the user asks Hermes to write, modify, debug, refactor, or review code.",
        ("task statement", "repo context", "constraints", "target files or discovered touchpoints"),
        ("changed files", "verification evidence", "remaining risks"),
        ("requested behavior is implemented", "tests or checks pass", "known gaps are reported"),
        ("run the smallest relevant tests", "inspect generated skill output when routing changed"),
        "If the request is underspecified, ask one concise clarification question before editing.",
        ("run_started", "coding_delegation_recorded", "verification_recorded"),
        "Record prepared coding delegation with omh coding delegate; record observed execution only when Hermes exposes a separate coding, review, or verification lane.",
        "metadata_only",
        quality_tier="handoff-gated",
        quality_bar=(
            "Clarify scope before edits when target behavior, files, or verification are missing.",
            "Attach acceptance criteria, verification expectations, and review expectations to the prepared handoff.",
            "Report coding progress from lifecycle evidence, not from the existence of a prepared prompt.",
        ),
        evidence_ladder=(
            "coding_delegation_prepared",
            "executor_dispatch_observed",
            "executor_result_observed",
            "verification_recorded",
            "review_ci_merge_recorded_when_required",
        ),
        wrapper_actions=(
            "accept_plan",
            "show_prompt_handoff",
            "copy_prompt_handoff",
            "choose_executor",
            "send_to_executor",
            "send_to_codex",
            "show_status",
            "record_result",
        ),
        overclaim_guards=(
            "A prepared coding_delegation.json is not implementation evidence.",
            "Executor completion is not review, CI, merge-readiness, or merge evidence.",
        ),
    ),
    HarnessDefinition(
        "goal-execution",
        "Keep long-running work tied to explicit goals, checkpoints, and durable evidence.",
        "Use when the task has multiple milestones, durable state, or finish-until-done pressure.",
        ("goal statement", "acceptance criteria", "current checkpoint", "blocked or pending stories", "linked runtime run ids when coding evidence is explicitly required"),
        ("goal_ledger/v1 updates", "checkpoint evidence", "goal_completion_gate/v1 result", "goal_status_card/v1 or goal_continuation/v1 next action"),
        ("current goal is complete or explicitly blocked", "checkpoint evidence is recorded", "completion gate is ready before final completion copy"),
        ("compare artifacts against acceptance criteria", "record fresh evidence before completion", "inspect explicitly linked runtime runs before treating coding work as observed"),
        "If Hermes has no goal tool, use a local checklist or file-backed ledger and still name the next action.",
        ("goal_started", "checkpoint_recorded", "goal_completed_or_blocked"),
        "Record goal/delegation participants only when the active Hermes runtime exposes them.",
        "metadata_only",
        quality_tier="checkpoint-gated",
        quality_bar=(
            "Create or reference a durable goal artifact before long-running progress claims.",
            "Checkpoint complete, blocked, and failed states with evidence.",
            "Use summary-only rejection when a goal_completion_gate/v1 blocks completion.",
            "Surface continue_goal, show_status, record_checkpoint, record_blocker, or record_completion as the next action.",
            "Run final verification and review gates before reporting a goal complete.",
        ),
        evidence_ladder=("goal_created", "story_started", "checkpoint_recorded", "quality_gate_recorded", "goal_closed"),
        wrapper_actions=("continue_goal", "show_status", "record_checkpoint", "record_blocker", "record_completion"),
        overclaim_guards=(
            "A goal ledger entry is not proof that executor work ran.",
            "Prepared or unlinked runtime artifacts cannot satisfy a coding-linked goal unless the goal explicitly references that run.",
            "Intermediate checkpoints cannot replace final verification and review evidence.",
        ),
    ),
    HarnessDefinition(
        "planning",
        "Turn clarified requirements into an execution-ready plan with tradeoffs and tests.",
        "Use before implementation when architecture, sequencing, or validation shape matters.",
        ("requirements", "constraints", "known facts", "non-goals"),
        ("PRD or plan", "test strategy", "handoff guidance"),
        ("plan has acceptance criteria", "risks and alternatives are explicit"),
        ("review option consistency", "verify testability before execution"),
        "If consensus review is unavailable, do a sequential planner -> reviewer pass.",
        ("plan_started", "options_reviewed", "handoff_recorded"),
        "Record planner, architect, or reviewer delegation only when observed in Hermes metadata or wrapper logs.",
        "metadata_only",
        quality_tier="acceptance-gated",
        quality_bar=(
            "Make goals, non-goals, decision drivers, options, risks, and test strategy explicit.",
            "Record at least one rejected option and why it lost before presenting the preferred path.",
            "Tie every acceptance criterion to a validation command, artifact, or explicit manual evidence gap.",
            "Keep draft plans unapproved until a user or wrapper accepts them.",
            "Prepare coding handoff guidance only after acceptance.",
        ),
        evidence_ladder=(
            "request_clarified",
            "plan_drafted",
            "option_tradeoffs_recorded",
            "test_strategy_recorded",
            "acceptance_recorded",
            "handoff_ready",
        ),
        wrapper_actions=("accept_plan", "revise_plan", "cancel", "prepare_handoff"),
        overclaim_guards=(
            "A draft plan is not execution or review evidence.",
            "Unobserved architect or critic review stays not_observed.",
        ),
    ),
    HarnessDefinition(
        "research",
        "Gather current or source-backed evidence before planning or coding handoff.",
        "Use when the request needs web/current/official source evidence or source comparison.",
        ("research question", "source boundaries", "recency or environment constraints"),
        ("source-backed synthesis", "links or citations", "confidence and residual uncertainty"),
        ("claims are source-backed", "retrieval limits and dates are explicit"),
        ("prefer official or primary sources", "separate evidence from inference"),
        "If web access is unavailable, state the retrieval gap and fall back to best available local evidence.",
        ("research_started", "source_checked", "synthesis_recorded"),
        "Record a research lane only when Hermes or the wrapper exposes source/research evidence; otherwise summarize retrieval limits explicitly.",
        "metadata_only",
        quality_tier="source-gated",
        quality_bar=(
            "Scope the research question, source boundaries, recency, and jurisdiction or version assumptions before retrieval.",
            "Use official or primary sources first when they can answer the question.",
            "Record source quality, conflicting evidence, and retrieval gaps before synthesis.",
            "Separate source evidence, inference, confidence, and retrieval limits.",
            "Record dates or version boundaries for unstable facts.",
        ),
        evidence_ladder=(
            "research_question_scoped",
            "primary_sources_checked",
            "conflicts_checked",
            "evidence_synthesized",
            "uncertainty_recorded",
        ),
        wrapper_actions=("show_sources", "ask_followup", "prepare_plan"),
        overclaim_guards=(
            "Research synthesis is not implementation evidence.",
            "Unavailable web access must be reported as a retrieval gap.",
        ),
    ),
    HarnessDefinition(
        "business-research",
        "Prepare source-backed business research briefs with evidence and inference boundaries.",
        "Use when a business, market, customer, or operational question needs source-scoped research before strategy, meetings, or handoff.",
        ("business question", "source boundary", "recency or market scope"),
        ("evidence table", "inference summary", "confidence and residual uncertainty"),
        ("source boundaries are explicit", "evidence and inference are separated", "uncertainty is recorded"),
        ("check source quality", "record missing-source gaps", "separate observed evidence from synthesis"),
        "If sources are not available, label the result as a research plan or local-context synthesis rather than observed research.",
        ("business_research_scoped", "business_source_checked", "business_synthesis_recorded"),
        "Record business research only when Hermes or the wrapper observes sources or captures a research brief.",
        "metadata_only",
        quality_tier="source-gated",
        quality_bar=(
            "Scope the business question and source boundary before synthesis.",
            "Separate observed sources, inferred trends, confidence, and uncertainty.",
            "Feed strategy or meeting work without treating the research brief as execution evidence.",
        ),
        evidence_ladder=(
            "business_question_scoped",
            "source_boundary_recorded",
            "source_evidence_recorded",
            "business_synthesis_recorded",
            "uncertainty_recorded",
        ),
        wrapper_actions=("show_sources", "ask_followup", "prepare_strategy_brief", "show_status"),
        overclaim_guards=(
            "A research brief is not proof that sources were fetched unless source evidence is observed.",
            "Research synthesis is not a decision, implementation, or verification result.",
        ),
    ),
    HarnessDefinition(
        "strategy-synthesis",
        "Turn goals and evidence into strategy options, tradeoffs, and decision-ready notes.",
        "Use when the request asks for strategy, recommendations, decision notes, or leadership-ready synthesis.",
        ("goal", "evidence summary", "constraints", "decision owner"),
        ("options", "tradeoffs", "recommendation", "decision note"),
        ("decision scope is explicit", "tradeoffs are named", "assumptions and follow-ups are recorded"),
        ("compare options", "tie recommendation to evidence", "record rejected alternatives"),
        "If decision authority or evidence is missing, produce assumptions and next questions instead of a final decision.",
        ("strategy_scope_recorded", "options_recorded", "decision_note_recorded"),
        "Record strategy synthesis as Hermes-retained work; record execution only after a later accepted handoff is observed.",
        "metadata_only",
        quality_tier="decision-gated",
        quality_bar=(
            "Name the decision, drivers, options, tradeoffs, recommendation, and assumptions.",
            "Keep draft recommendations separate from accepted decisions.",
            "Convert implementation follow-ups into explicit later plans or handoffs.",
        ),
        evidence_ladder=(
            "decision_scope_recorded",
            "options_recorded",
            "tradeoffs_recorded",
            "recommendation_recorded",
            "decision_status_recorded",
        ),
        wrapper_actions=("show_brief", "revise_brief", "record_decision", "show_status"),
        overclaim_guards=(
            "A strategy brief is not an accepted decision.",
            "A recommendation is not implementation, review, CI, or merge evidence.",
        ),
    ),
    HarnessDefinition(
        "meeting-facilitation",
        "Prepare agendas, discussion prompts, decisions, and record templates.",
        "Use when the request asks Hermes to prepare a meeting, agenda, discussion guide, or follow-up record template.",
        ("meeting goal", "audience", "context", "decision topics"),
        ("agenda", "discussion prompts", "decisions needed", "record template"),
        ("agenda is coherent", "decisions needed are explicit", "actual outcomes remain unobserved"),
        ("check missing context", "separate prep from outcomes", "include record template"),
        "If the meeting already happened, ask for observed notes before treating decisions as outcomes.",
        ("meeting_context_scoped", "agenda_recorded", "record_template_recorded"),
        "Record meeting prep only as prepared content unless observed meeting notes or decisions are supplied.",
        "metadata_only",
        quality_tier="facilitation-gated",
        quality_bar=(
            "Prepare agenda topics, prompts, decisions needed, and a record template from available context.",
            "Keep proposed agenda and action items separate from observed meeting outcomes.",
            "Ask for missing context that would change participants, decisions, or timing.",
        ),
        evidence_ladder=(
            "meeting_goal_scoped",
            "agenda_recorded",
            "discussion_prompts_recorded",
            "decisions_needed_recorded",
            "record_template_ready",
        ),
        wrapper_actions=("show_agenda", "revise_brief", "record_decision", "show_status"),
        overclaim_guards=(
            "A prepared agenda is not evidence that a meeting happened.",
            "Draft action items are not observed decisions.",
        ),
    ),
    HarnessDefinition(
        "customer-insight-triage",
        "Cluster customer feedback and choose the next workflow without defaulting to coding.",
        "Use when feedback, bugs, feature asks, or customer signals need classification before planning or implementation.",
        ("feedback items or summary", "source boundary", "product area"),
        ("clusters", "severity or opportunity ranking", "next workflow recommendation"),
        ("source boundary is explicit", "clusters are labeled", "next workflow is conservative"),
        ("separate bug signals from feature asks", "rank severity and opportunity", "avoid default coding handoff"),
        "If feedback items are too vague, ask for source or sample items before ranking severity.",
        ("feedback_source_scoped", "feedback_cluster_recorded", "next_workflow_recorded"),
        "Record feedback triage as Hermes-retained analysis; record coding handoff only after explicit accepted coding intent.",
        "metadata_only",
        quality_tier="triage-gated",
        quality_bar=(
            "Scope the feedback source before clustering.",
            "Separate bug signals, feature asks, severity, opportunity, and evidence gaps.",
            "Recommend research, strategy, planning, or coding only as a next workflow, not as observed execution.",
        ),
        evidence_ladder=(
            "feedback_source_scoped",
            "clusters_recorded",
            "severity_opportunity_recorded",
            "next_workflow_recommended",
        ),
        wrapper_actions=("show_triage", "ask_followup", "prepare_plan", "show_status"),
        overclaim_guards=(
            "Feedback triage is not a roadmap, implementation plan, or coding handoff by default.",
            "A bug signal is not proof that a fix was implemented or verified.",
        ),
    ),
    HarnessDefinition(
        "ops-review",
        "Summarize observed operating status, risks, blockers, priorities, and follow-up actions.",
        "Use when recurring work needs a weekly/status/operating review with evidence boundaries.",
        ("status evidence", "scope", "time window", "known risks"),
        ("status summary", "risks", "blockers", "priorities", "follow-up actions"),
        ("status claims are evidence-bound", "risks and blockers are separated", "follow-ups are explicit"),
        ("check evidence gaps", "separate facts from risks", "record follow-up ownership when known"),
        "If evidence is missing, produce a review scaffold and mark unknowns instead of claiming status.",
        ("ops_scope_recorded", "status_recorded", "followups_recorded"),
        "Record ops review as Hermes-retained status work; execution evidence requires later observed task records.",
        "metadata_only",
        quality_tier="status-gated",
        quality_bar=(
            "Tie status claims to observed evidence or mark them as unknown.",
            "Separate risks, blockers, priorities, and follow-up actions.",
            "Do not infer review, CI, release, or merge readiness from an ops summary alone.",
        ),
        evidence_ladder=(
            "review_scope_recorded",
            "status_evidence_recorded",
            "risks_blockers_recorded",
            "priorities_recorded",
            "followups_recorded",
        ),
        wrapper_actions=("show_status", "record_blocker", "record_checkpoint", "prepare_plan"),
        overclaim_guards=(
            "An ops review is not release, CI, review, merge, or implementation evidence.",
            "Missing evidence must stay unknown, not inferred green.",
        ),
    ),
    HarnessDefinition(
        "app-delivery-loop",
        "Run complete app operation loops from idea through decision, handoff, release, deploy, and monitor status.",
        "Use when a Hermes wrapper needs a finished-product-feeling path for idea-to-deploy, CTO loops, or deploy-and-monitor work without hidden coding or infrastructure execution.",
        ("idea or release request", "success metric", "scope constraints", "evidence sources"),
        ("stage rail", "decision gates", "handoff or retained-work plan", "deploy/monitor status boundary"),
        ("next stage is accepted or blocked", "unobserved deploy/monitor claims stay explicit", "coding work has selected executor guidance when needed"),
        ("check every stage has an owner", "separate prepared from observed", "record deploy and monitor only from evidence"),
        "If release scope, owner, or evidence is missing, show the loop scaffold and ask for the smallest missing decision before advancing.",
        ("delivery_loop_scoped", "decision_gate_recorded", "handoff_or_release_status_recorded"),
        "Record app delivery loop evidence only when Hermes, a wrapper, or an operator observes stage acceptance, handoff, deploy, or monitoring events.",
        "metadata_only",
        quality_tier="delivery-gated",
        quality_bar=(
            "Name the product or release objective, user/customer value, success metric, non-goals, and owner.",
            "Represent idea, decision, plan, handoff, verification, release, deploy, and monitor as separate stages.",
            "Keep coding work executor-neutral until a selected executor is chosen and a handoff is accepted.",
            "Keep deploy, monitoring, rollback, incident, review, CI, and merge claims unavailable until observed evidence exists.",
        ),
        evidence_ladder=(
            "loop_scope_recorded",
            "decision_gate_recorded",
            "plan_or_release_gate_accepted",
            "handoff_prepared_if_needed",
            "verification_release_gate_recorded",
            "deploy_monitor_observed_when_available",
        ),
        wrapper_actions=(
            "show_delivery_loop",
            "accept_plan",
            "choose_executor",
            "prepare_handoff",
            "record_deploy",
            "record_monitor_signal",
            "show_status",
        ),
        overclaim_guards=(
            "A prepared app delivery loop is not implementation, deploy, monitor, rollback, incident, review, CI, merge-readiness, or merge evidence.",
            "A CTO loop recommendation is not an accepted decision unless decision evidence is recorded.",
            "A health watchlist is not observed health evidence.",
        ),
    ),
    HarnessDefinition(
        "goal-loop",
        "Run ambitious goal loops through task discovery, distribution, execution, verification, next-task decisions, runtime ticks with deterministic queue shapes, handoff, feedback, waiting, and resumable status without hidden execution.",
        "Use when a direct loop invocation or explicit long-horizon goal needs repeated cycles over automation, worktree, skill, connector, and subagent building blocks until evidence, authority, context, or external waiting stops the next step.",
        ("north-star goal summary", "reframed implementable target", "success criteria", "permission profile", "feedback or wait signal"),
        ("loop_start_card/v1 setup card", "loop_cycle/v1 artifact", "loop_engineering/v1 pipeline/building-block snapshot", "loop cost_policy for bounded reads and verifier restraint", "loop_runtime/v1 queue entry with loop policy refs", "loop_queue_handoff/v1 actionable handoff", "loop_subagent_result_contract/v1 when a subagent is planned", "loop_status_card/v1 next action", "permission envelope", "linked goal or runtime evidence references when available"),
        ("next loop step is clear", "runtime tick queue is prepared, observed, or blocked with a reason", "automation/worktree/skill/connector/subagent block states are visible", "permission boundaries are explicit", "external waiting and context exhaustion are recorded", "goal completion claims are delegated to goal_ledger/v1"),
        ("validate loop_cycle/v1", "inspect loop_engineering/v1 snapshot", "inspect loop_runtime/v1 queue", "inspect loop_status_card/v1", "inspect loop_queue_handoff/v1 when a queued item is actionable", "check linked goal_completion_gate/v1 before completion copy"),
        "If no wrapper or CLI artifact is available, keep a visible checklist with the same permission profile and evidence boundaries.",
        ("loop_started", "permission_profile_recorded", "feedback_gate_recorded", "loop_status_card_rendered"),
        "Record loop state as Hermes-retained orchestration; record executor dispatch, implementation, review, CI, merge, and external publication only when observed by a linked runtime or operator artifact.",
        "metadata_only",
        quality_tier="loop-gated",
        quality_bar=(
            "Confirm the direct loop trigger, north-star goal, reframe, success criteria, and permission profile before cycling.",
            "Separate implementable internal work from external outcomes such as stars, market reaction, adoption, or social distribution.",
            "Continue automatically only inside the selected authority envelope; otherwise surface a permission action.",
            "Use runtime ticks with deterministic queue shapes to prepare automation, worktree, skill, connector, and subagent states, but require separate observed evidence before claiming those steps ran.",
            "Keep loop_engineering/v1 focused on bounded state and evidence refs rather than dumping large intermediate context into the parent loop.",
            "Use fan-out, adversarial verification, tournament, or triage-batch workflow patterns for research validation, support triage, or implementation review only when the extra lanes add evidence value.",
            "Keep the schema scaffold stable for repeated ticks and avoid re-scanning or re-emitting large context when evidence refs are enough.",
            "Treat feedback as a gate: clear internal actionable gaps continue the loop; external waiting records a wait state.",
            "Never report goal completion from loop state unless linked goal_ledger/v1 completion evidence is ready.",
        ),
        evidence_ladder=(
            "loop_triggered",
            "goal_reframed",
            "permission_profile_recorded",
            "runtime_tick_queued",
            "research_plan_handoff_cycle_recorded",
            "feedback_gate_evaluated",
            "wait_or_resume_boundary_recorded",
        ),
        wrapper_actions=(
            "choose_permission_profile",
            "start_loop",
            "run_loop_tick",
            "show_loop_queue",
            "prepare_loop_handoff",
            "observe_loop_queue",
            "block_loop_queue",
            "show_loop_status",
            "prepare_handoff",
            "choose_executor",
            "show_status",
        ),
        overclaim_guards=(
            "A loop_cycle/v1 artifact is not proof that coding, review, CI, merge, or external publication happened.",
            "A loop_runtime/v1 tick is not proof that a worktree, subagent, connector, or executor actually ran.",
            "A full-loop permission profile is still bounded by observed evidence and explicit external-production authority.",
            "External outcomes stay waiting_external_observation until evidence is recorded.",
        ),
    ),
    HarnessDefinition(
        "deep-interview",
        "Clarify intent and boundaries one question at a time before planning or execution.",
        "Use when intent, scope, non-goals, or decision authority are unclear.",
        ("initial idea", "current ambiguity", "known repo facts"),
        ("clarified spec", "non-goals", "decision boundaries", "acceptance criteria"),
        ("ambiguity is low enough", "non-goals and decision boundaries are explicit"),
        ("pressure-test assumptions", "capture transcript or summary"),
        "If structured question UI is unavailable, ask one direct question in the current surface.",
        ("interview_started", "question_asked", "clarity_recorded"),
        "Record a delegated interviewer only when Hermes exposes that lane; otherwise record sequential clarification.",
        "metadata_only",
        quality_tier="clarity-gated",
        quality_bar=(
            "Name the missing decision, why it matters, and the smallest answer that would unblock the next step.",
            "Ask one blocking question tied to a missing decision.",
            "Use discovered facts before asking the user for information already available locally.",
            "Produce a clarified brief with non-goals, acceptance criteria, and remaining unknowns before planning or handoff.",
        ),
        evidence_ladder=("ambiguity_identified", "blocking_question_asked", "answer_recorded", "clarified_brief_ready"),
        wrapper_actions=("answer:clarify", "cancel", "rerun_plan"),
        overclaim_guards=(
            "A clarification question is not a plan approval.",
            "Do not start a handoff while the blocking decision is unanswered.",
        ),
    ),
    HarnessDefinition(
        "architect",
        "Evaluate system boundaries, integration choices, and long-term maintainability.",
        "Use when a plan touches architecture, runtime integration, extension boundaries, or shared contracts.",
        ("plan", "context", "constraints", "existing architecture evidence"),
        ("architecture verdict", "tradeoff tension", "required changes or clear approval"),
        ("boundary risks are addressed", "chosen approach fits current architecture"),
        ("steelman the strongest antithesis", "check integration claims against evidence"),
        "If delegation is unavailable, run a separate self-review pass before coding.",
        ("architecture_review_started", "tradeoff_recorded", "verdict_recorded"),
        "Record architect delegation only when Hermes exposes an architect lane or wrapper-side role result.",
        "metadata_only",
        quality_tier="boundary-gated",
        quality_bar=(
            "Check the proposed change against documented product and module boundaries.",
            "Name rejected alternatives and long-term maintenance tradeoffs.",
            "Require clear approval or concrete requested changes before implementation.",
        ),
        evidence_ladder=("architecture_context_loaded", "tradeoffs_recorded", "boundary_verdict_recorded"),
        wrapper_actions=("show_review", "revise_plan", "approve_plan"),
        overclaim_guards=(
            "Sequential self-review is not observed architect delegation.",
            "Architecture approval does not imply implementation or test success.",
        ),
    ),
    HarnessDefinition(
        "critic",
        "Challenge plan consistency, quality criteria, and missing verification.",
        "Use after planning or before release when a bad assumption would be costly.",
        ("plan", "test spec", "architect review", "user constraints"),
        ("approval or requested changes", "critical findings", "residual risks"),
        ("quality criteria are testable", "risks have mitigations", "alternatives are fair"),
        ("check principle-option consistency", "reject vague acceptance criteria"),
        "If no critic role exists, do a bug-first checklist review and cite concrete evidence.",
        ("critic_review_started", "finding_recorded", "verdict_recorded"),
        "Record critic delegation only when Hermes exposes a critic lane or wrapper-side role result.",
        "metadata_only",
        quality_tier="finding-gated",
        quality_bar=(
            "Challenge plan consistency, missing verification, and weak acceptance criteria.",
            "Rank concrete findings before summaries.",
            "Approve only when residual risks and test gaps are explicit.",
        ),
        evidence_ladder=("review_scope_loaded", "findings_recorded", "verdict_recorded", "residual_risk_recorded"),
        wrapper_actions=("show_findings", "request_changes", "approve_plan"),
        overclaim_guards=(
            "A critic verdict is not code-review evidence unless tied to actual diff/files.",
            "Approval cannot erase missing downstream verification.",
        ),
    ),
    HarnessDefinition(
        "qa-specialist",
        "Design adversarial scenarios and verify user-visible behavior before completion.",
        "Use when changes affect workflows, installer behavior, docs examples, or routing claims.",
        ("acceptance criteria", "changed behavior", "fixtures or runnable commands"),
        ("test matrix", "hostile scenarios", "pass/fail evidence"),
        ("critical scenarios pass", "known manual gaps are listed"),
        ("run targeted tests", "cover failure modes and recovery paths"),
        "If runtime automation is unavailable, use fixtures and document manual checks.",
        ("qa_started", "scenario_recorded", "pass_fail_recorded"),
        "Record QA delegation only when Hermes exposes a QA lane or wrapper-side QA result.",
        "metadata_only",
        quality_tier="scenario-gated",
        quality_bar=(
            "Derive adversarial scenarios from user-visible behavior and changed surfaces.",
            "Record pass/fail evidence for critical scenarios.",
            "Turn discovered code fixes into executor handoffs.",
        ),
        evidence_ladder=("scenario_matrix_defined", "checks_run", "pass_fail_recorded", "fix_followup_recorded_if_needed"),
        wrapper_actions=("show_status", "record_check", "record_blocker"),
        overclaim_guards=(
            "A scenario list is not pass evidence.",
            "Failed QA cannot be summarized as complete without a blocker or fix record.",
        ),
    ),
    HarnessDefinition(
        "docs-specialist",
        "Keep public docs accurate, installable, and aligned with actual behavior.",
        "Use whenever user-facing commands, routing behavior, examples, or release posture change.",
        ("changed behavior", "commands", "limitations", "audience"),
        ("README/docs updates", "examples", "troubleshooting notes"),
        ("docs match behavior", "claims are conservative", "examples are reproducible"),
        ("run public-content scans", "verify commands and file references"),
        "If behavior is not implemented yet, label it as roadmap instead of current capability.",
        ("docs_review_started", "claim_checked", "docs_updated"),
        "Record docs delegation only when Hermes exposes a docs lane or wrapper-side docs result.",
        "metadata_only",
        quality_tier="claim-gated",
        quality_bar=(
            "Check public claims against implemented behavior and known limitations.",
            "Keep examples reproducible and avoid presenting roadmap as current capability.",
            "Regenerate generated references from catalog data instead of hand-editing them.",
        ),
        evidence_ladder=("claims_scoped", "docs_updated", "generated_docs_checked", "public_claims_verified"),
        wrapper_actions=("show_docs", "record_claim_check", "show_status"),
        overclaim_guards=(
            "Documentation of a future surface is not proof that evidence was observed.",
            "Generated docs must match catalog data before release claims are made.",
        ),
    ),
]


_PRIMARY_HARNESSES = {
    "ralph": "goal-execution",
    "ultragoal": "goal-execution",
    "deep-interview": "deep-interview",
    "team": "goal-execution",
    "ultrawork": "goal-execution",
    "web-research": "research",
    "research-brief": "business-research",
    "strategy-brief": "strategy-synthesis",
    "meeting-brief": "meeting-facilitation",
    "feedback-triage": "customer-insight-triage",
    "ops-review": "ops-review",
    "idea-to-deploy": "app-delivery-loop",
    "cto-loop": "app-delivery-loop",
    "deploy-and-monitor": "app-delivery-loop",
    "loop": "goal-loop",
    "ultraprocess": "goal-execution",
    "ultraqa": "qa-specialist",
    "plan": "planning",
    "ralplan": "planning",
    "code-review": "critic",
    "ai-slop-cleaner": "coding-handling",
    "best-practice-research": "research",
    "autoresearch-goal": "research",
    "performance-goal": "goal-execution",
    "wiki": "docs-specialist",
    "ask": "critic",
    "cancel": "goal-execution",
    "skill": "docs-specialist",
    "doctor": "qa-specialist",
}


def builtin_definitions() -> list[SkillDefinition]:
    return list(_DEFINITIONS)


def builtin_harnesses() -> list[HarnessDefinition]:
    return list(_HARNESSES)


def harness_definition(name: str) -> HarnessDefinition:
    for harness in _HARNESSES:
        if harness.name == name:
            return harness
    raise KeyError(name)


def harness_quality_contract(name: str) -> dict[str, object]:
    try:
        harness = harness_definition(name)
    except KeyError:
        return unknown_harness_quality_contract(name)
    return build_harness_quality_contract(
        harness=harness.name,
        quality_tier=harness.quality_tier,
        quality_bar=harness.quality_bar,
        evidence_ladder=harness.evidence_ladder,
        wrapper_actions=harness.wrapper_actions,
        overclaim_guards=harness.overclaim_guards,
    )


def primary_harness_for_skill(name: str) -> str:
    return _PRIMARY_HARNESSES.get(name, "coding-handling")


def coding_intent_for_skill(name: str) -> str:
    return _CODING_INTENT_BY_SKILL.get(name, "coding")


def coding_skills_for_intent(intent: str) -> tuple[str, ...]:
    return tuple(name for name, mapped_intent in _CODING_INTENT_BY_SKILL.items() if mapped_intent == intent)


def coding_terms_for_intent(intent: str) -> tuple[str, ...]:
    return CODING_INTENT_TERMS.get(intent, ())


def retained_delegation_skill_names() -> tuple[str, ...]:
    return tuple(
        definition.name
        for definition in _DEFINITIONS
        if definition.delegation_boundary in {"retained", "retained-catalog-intent"}
    )


def catalog_intent_delegation_skill_names() -> tuple[str, ...]:
    return tuple(
        definition.name
        for definition in _DEFINITIONS
        if definition.delegation_boundary == "retained-catalog-intent"
    )


MEMORY_CONTEXT_POLICIES = ("compact", "explicit")
_EXPLICIT_MEMORY_CONTEXT_SKILLS = (
    "ralph",
    "ultragoal",
    "loop",
    "ultraprocess",
    "team",
    "ultrawork",
    "idea-to-deploy",
    "cto-loop",
    "deploy-and-monitor",
    "ultraqa",
    "plan",
    "ralplan",
    "code-review",
    "ai-slop-cleaner",
    "performance-goal",
    "ask",
)


def memory_context_policy_for_skill(name: str) -> str:
    return "explicit" if name in _EXPLICIT_MEMORY_CONTEXT_SKILLS else "compact"


def explicit_memory_context_skill_names() -> tuple[str, ...]:
    return _EXPLICIT_MEMORY_CONTEXT_SKILLS


CORE_SKILLS = [definition.name for definition in _DEFINITIONS]
DESCRIPTIONS = {definition.name: definition.description for definition in _DEFINITIONS}
